import type { GlobePoint } from "./Globe";

export type Event = GlobePoint & {
  title: string;
  year: number;
  place: string;
  field: string;
  weight: number;
  years?: [number, number];
  spaceScale?: number;
  timeScale?: number;
};
export type Focus = {
  name: string;
  note: string;
  years: [number, number];
  view: GlobePoint & { distance: number };
  deck: Event[];
};
type Calibration = Partial<Pick<Event, "years" | "spaceScale" | "timeScale">>;
type Row = [
  title: string,
  year: number,
  lat: number,
  lon: number,
  place: string,
  field: string,
  weight: number,
  calibration?: Calibration,
];

export const PRESENT = 2026;

// Per-field calibration. `years` is the window the timeline exposes for the
// question; `spaceScale` (km) and `timeScale` (years) are the L2 normalisers.
// Fields not listed fall back to the full −4000..present window, an 1,800 km
// spatial scale, and an era-adjusted time scale. Individual events may
// override any of these.
export const FIELD_RULES: Record<string, Calibration> = {
  Baseball: { years: [1840, PRESENT], spaceScale: 500, timeScale: 10 },
  Football: { years: [1850, PRESENT], spaceScale: 900, timeScale: 8 },
  Olympics: { years: [1890, PRESENT], spaceScale: 900, timeScale: 6 },
  Athletics: { years: [1850, PRESENT], spaceScale: 800, timeScale: 8 },
  Boxing: { years: [1850, PRESENT], spaceScale: 900, timeScale: 8 },
  Hockey: { years: [1870, PRESENT], spaceScale: 700, timeScale: 8 },
  Tennis: { years: [1850, PRESENT], spaceScale: 600, timeScale: 10 },
  Cycling: { years: [1850, PRESENT], spaceScale: 600, timeScale: 10 },
  Sport: { years: [1700, PRESENT], spaceScale: 800, timeScale: 15 },
  Film: { years: [1880, PRESENT], spaceScale: 700, timeScale: 8 },
  Aviation: { years: [1780, PRESENT], spaceScale: 900, timeScale: 10 },
  "Space exploration": {
    years: [1940, PRESENT],
    spaceScale: 1500,
    timeScale: 5,
  },
  Computing: { years: [1820, PRESENT], spaceScale: 800, timeScale: 8 },
  Communications: { years: [1790, PRESENT], spaceScale: 1000, timeScale: 10 },
  Engineering: { years: [1700, PRESENT], spaceScale: 800, timeScale: 12 },
  Infrastructure: { years: [1700, PRESENT], spaceScale: 800, timeScale: 12 },
  Archaeology: { years: [1700, PRESENT], spaceScale: 1200, timeScale: 12 },
  "Civil rights": { years: [1750, PRESENT], spaceScale: 800, timeScale: 10 },
  "Labor history": { years: [1750, PRESENT], spaceScale: 800, timeScale: 10 },
  "Women’s history": {
    years: [1750, PRESENT],
    spaceScale: 1000,
    timeScale: 10,
  },
  Decolonization: { years: [1750, PRESENT], spaceScale: 1200, timeScale: 8 },
  Music: { years: [1500, PRESENT], spaceScale: 700, timeScale: 12 },
  Medicine: { years: [1500, PRESENT], spaceScale: 900, timeScale: 15 },
  Chemistry: { years: [1600, PRESENT], spaceScale: 900, timeScale: 15 },
  Physics: { years: [1500, PRESENT], spaceScale: 900, timeScale: 15 },
  Biology: { years: [1500, PRESENT], spaceScale: 900, timeScale: 15 },
  "Ancient history": { spaceScale: 2200 },
  "Classical antiquity": { spaceScale: 2000 },
  Mathematics: { spaceScale: 1500 },
};

const ROWS: Row[] = [
  [
    "Constantine wins the Battle of the Milvian Bridge.",
    312,
    41.94,
    12.47,
    "Rome, Italy",
    "Imperial politics",
    4,
  ],
  [
    "Pride and Prejudice is first published.",
    1813,
    51.51,
    -0.13,
    "London, England",
    "Literature",
    3,
  ],
  [
    "The Gutenberg Bible comes off the press.",
    1455,
    50,
    8.27,
    "Mainz, Germany",
    "Technology",
    4,
  ],
  [
    "A Malian emperor’s pilgrimage caravan spends so much gold it depresses the local currency for years.",
    1324,
    30.04,
    31.24,
    "Cairo, Egypt",
    "Economic history",
    3,
  ],
  [
    "An Ottoman sultan’s cannon breach the walls of the thousand-year-old Byzantine capital.",
    1453,
    41.01,
    28.98,
    "Constantinople",
    "Military history",
    5,
  ],
  [
    "A successful slave revolt founds the world’s first Black republic.",
    1804,
    19.45,
    -72.68,
    "Gonaïves, Haiti",
    "Revolution",
    4,
  ],
  [
    "The Meiji Restoration is proclaimed.",
    1868,
    35.68,
    139.76,
    "Tokyo, Japan",
    "State formation",
    4,
  ],
  [
    "The Wright brothers make the first controlled powered flight.",
    1903,
    36.02,
    -75.67,
    "Kitty Hawk, USA",
    "Aviation",
    3,
  ],
  [
    "India becomes independent from British rule.",
    1947,
    28.61,
    77.21,
    "New Delhi, India",
    "Decolonization",
    5,
  ],
  [
    "The double-helix structure of DNA is published.",
    1953,
    52.21,
    0.12,
    "Cambridge, England",
    "Science",
    2,
  ],
  [
    "A papal-brokered treaty divides the newly found world between two Iberian crowns.",
    1494,
    41.5,
    -5,
    "Tordesillas, Spain",
    "Diplomacy",
    4,
  ],
  [
    "Hiram Bingham reaches Machu Picchu.",
    1911,
    -13.16,
    -72.55,
    "Cusco Region, Peru",
    "Archaeology",
    2,
  ],
  [
    "French soldiers uncover the Rosetta Stone.",
    1799,
    31.4,
    30.42,
    "Rashid, Egypt",
    "Linguistics",
    2,
  ],
  [
    "King John seals Magna Carta.",
    1215,
    51.44,
    -0.57,
    "Runnymede, England",
    "Legal history",
    4,
  ],
  [
    "A Zulu army annihilates a British column beneath a rocky hill.",
    1879,
    -28.36,
    30.65,
    "Isandlwana, South Africa",
    "Colonial history",
    3,
  ],
  [
    "The Song dynasty is founded.",
    960,
    34.8,
    114.31,
    "Kaifeng, China",
    "Dynastic history",
    3,
  ],
  [
    "Ashoka conquers Kalinga.",
    -261,
    20.27,
    85.84,
    "Odisha, India",
    "Ancient history",
    3,
  ],
  [
    "The earliest known writing appears on clay tablets in a Sumerian city.",
    -3200,
    31.32,
    45.64,
    "Uruk, Mesopotamia",
    "Writing systems",
    3,
  ],
  [
    "A pharaoh abandons the old gods and builds a new capital for his sun disc.",
    -1346,
    27.65,
    30.9,
    "Amarna, Egypt",
    "Religious history",
    2,
  ],
  [
    "The first modern Olympic Games open.",
    1896,
    37.98,
    23.73,
    "Athens, Greece",
    "Sport",
    2,
  ],
  [
    "The gold rush begins after discovery at Sutter’s Mill.",
    1848,
    38.8,
    -120.89,
    "Coloma, USA",
    "Migration",
    2,
  ],
  [
    "European powers convene to carve up Africa among themselves.",
    1884,
    52.52,
    13.4,
    "Berlin, Germany",
    "Geopolitics",
    5,
  ],
  [
    "The first successful smallpox vaccination is administered.",
    1796,
    51.71,
    -2.5,
    "Berkeley, England",
    "Medicine",
    2,
  ],
  [
    "A canal joining the Atlantic and Pacific opens to traffic.",
    1914,
    9.08,
    -79.68,
    "Panama",
    "Infrastructure",
    3,
  ],
  // ── Sport (calibrated tightly: modern, geographically specific) ──────────
  [
    "The first modern World Series begins.",
    1903,
    42.35,
    -71.1,
    "Boston, USA",
    "Baseball",
    2,
    { spaceScale: 700, timeScale: 18 },
  ],
  [
    "Jackie Robinson makes his major-league debut.",
    1947,
    40.67,
    -73.97,
    "Brooklyn, USA",
    "Baseball",
    2,
    { timeScale: 12 },
  ],
  [
    "Babe Ruth hits his sixtieth home run of the season.",
    1927,
    40.83,
    -73.93,
    "New York, USA",
    "Baseball",
    1,
    { spaceScale: 450 },
  ],
  [
    "Bobby Thomson hits the ‘Shot Heard ’Round the World’.",
    1951,
    40.83,
    -73.94,
    "Polo Grounds, New York",
    "Baseball",
    1,
  ],
  [
    "Cal Ripken Jr. breaks Lou Gehrig’s consecutive-games record.",
    1995,
    39.28,
    -76.62,
    "Baltimore, USA",
    "Baseball",
    1,
  ],
  [
    "The Red Sox win their first World Series in 86 years.",
    2004,
    38.63,
    -90.19,
    "St. Louis, USA",
    "Baseball",
    2,
  ],
  [
    "The first international cricket match is played.",
    1844,
    40.73,
    -74,
    "New York, USA",
    "Sport",
    1,
    { spaceScale: 800, timeScale: 20 },
  ],
  [
    "The world’s oldest tennis championship is played for the first time.",
    1877,
    51.43,
    -0.21,
    "Wimbledon, England",
    "Tennis",
    2,
  ],
  [
    "The first Tour de France sets off.",
    1903,
    48.7,
    2.46,
    "Montgeron, France",
    "Cycling",
    2,
  ],
  [
    "Uruguay wins the first FIFA World Cup final.",
    1930,
    -34.89,
    -56.15,
    "Montevideo, Uruguay",
    "Football",
    3,
  ],
  [
    "Jesse Owens wins four gold medals at a Games staged as a fascist showcase.",
    1936,
    52.51,
    13.24,
    "Berlin, Germany",
    "Olympics",
    3,
  ],
  [
    "Roger Bannister runs the first sub-four-minute mile.",
    1954,
    51.75,
    -1.26,
    "Oxford, England",
    "Athletics",
    2,
  ],
  [
    "Seventeen-year-old Pelé wins the World Cup with Brazil.",
    1958,
    59.37,
    18.0,
    "Solna, Sweden",
    "Football",
    2,
  ],
  [
    "Muhammad Ali beats George Foreman in the ‘Rumble in the Jungle’.",
    1974,
    -4.33,
    15.31,
    "Kinshasa, Zaire",
    "Boxing",
    3,
  ],
  [
    "The US hockey team beats the Soviets in the ‘Miracle on Ice’.",
    1980,
    44.28,
    -73.98,
    "Lake Placid, USA",
    "Hockey",
    2,
  ],
  [
    "Maradona scores the ‘Hand of God’ goal.",
    1986,
    19.3,
    -99.15,
    "Mexico City, Mexico",
    "Football",
    3,
  ],
  // ── Ancient & classical ──────────────────────────────────────────────────
  [
    "The largest of the pyramids is completed for the pharaoh Khufu.",
    -2560,
    29.98,
    31.13,
    "Giza, Egypt",
    "Architecture",
    4,
    { timeScale: 120, spaceScale: 1500 },
  ],
  [
    "An ancient king has his law code carved onto a basalt stele.",
    -1754,
    32.54,
    44.42,
    "Babylon, Mesopotamia",
    "Legal history",
    3,
    { timeScale: 100 },
  ],
  [
    "The Buddha preaches his first sermon in a deer park.",
    -528,
    25.38,
    83.02,
    "Sarnath, India",
    "Religious history",
    3,
    { timeScale: 80 },
  ],
  [
    "Confucius dies in his home state of Lu.",
    -479,
    35.6,
    116.99,
    "Qufu, China",
    "Philosophy",
    3,
    { timeScale: 60 },
  ],
  [
    "Outnumbered Athenians rout a Persian landing force on a coastal plain.",
    -490,
    38.15,
    23.97,
    "Marathon, Greece",
    "Military history",
    4,
  ],
  [
    "Socrates drinks hemlock after his conviction for impiety.",
    -399,
    37.97,
    23.72,
    "Athens, Greece",
    "Philosophy",
    4,
  ],
  [
    "Alexander routs Darius III at Gaugamela.",
    -331,
    36.56,
    43.44,
    "near Mosul, Iraq",
    "Military history",
    4,
  ],
  [
    "Euclid compiles the Elements.",
    -300,
    31.2,
    29.92,
    "Alexandria, Egypt",
    "Mathematics",
    3,
    { timeScale: 60 },
  ],
  [
    "Qin Shi Huang unifies China under one emperor.",
    -221,
    34.33,
    108.7,
    "Xianyang, China",
    "Dynastic history",
    4,
  ],
  [
    "Hannibal leads an army with war elephants over a mountain range in the Second Punic War.",
    -218,
    45.0,
    6.9,
    "Western Alps",
    "Military history",
    3,
    { spaceScale: 1200 },
  ],
  [
    "Julius Caesar is assassinated in the Senate.",
    -44,
    41.9,
    12.48,
    "Rome, Italy",
    "Imperial politics",
    5,
  ],
  [
    "Octavian’s fleet shatters that of Antony and Cleopatra.",
    -31,
    38.94,
    20.77,
    "Actium, Greece",
    "Naval history",
    3,
  ],
  [
    "A volcanic eruption buries two Roman towns under ash and pumice.",
    79,
    40.75,
    14.49,
    "Pompeii, Italy",
    "Disaster",
    4,
  ],
  [
    "Work begins on Hadrian’s Wall.",
    122,
    55.0,
    -2.3,
    "Northern England",
    "Architecture",
    2,
  ],
  [
    "Ptolemy completes his Geography.",
    150,
    31.2,
    29.92,
    "Alexandria, Egypt",
    "Cartography",
    2,
    { timeScale: 60 },
  ],
  [
    "Bishops gather at an imperial summons to settle the nature of Christ.",
    325,
    40.43,
    29.72,
    "Nicaea (İznik), Turkey",
    "Religious history",
    4,
  ],
  [
    "Visigoths sack a city that had not fallen to a foreign enemy in eight centuries.",
    410,
    41.9,
    12.48,
    "Rome, Italy",
    "Military history",
    3,
  ],
  [
    "A church council defines Christ as one person in two natures.",
    451,
    40.99,
    29.03,
    "Chalcedon, Turkey",
    "Religious history",
    2,
  ],
  [
    "Romulus Augustulus is deposed, ending the Western Roman Empire.",
    476,
    44.42,
    12.2,
    "Ravenna, Italy",
    "Imperial politics",
    4,
  ],
  [
    "Justinian issues his codification of Roman law.",
    529,
    41.01,
    28.98,
    "Constantinople",
    "Legal history",
    2,
  ],
  [
    "Hagia Sophia is dedicated.",
    537,
    41.01,
    28.98,
    "Constantinople",
    "Architecture",
    3,
  ],
  [
    "Bubonic plague devastates the Eastern Roman capital under Justinian.",
    541,
    41.01,
    28.98,
    "Constantinople",
    "Epidemics",
    2,
  ],
  // ── Medieval ─────────────────────────────────────────────────────────────
  [
    "Muhammad and his followers make the migration that begins the Islamic calendar.",
    622,
    24.47,
    39.61,
    "Medina, Arabia",
    "Religious history",
    4,
  ],
  [
    "A Frankish commander halts an Umayyad advance into western Europe.",
    732,
    47.39,
    0.69,
    "Tours, France",
    "Military history",
    3,
  ],
  [
    "Norse raiders sack an island monastery, shocking Christian Europe.",
    793,
    55.67,
    -1.8,
    "Lindisfarne, England",
    "Military history",
    2,
  ],
  [
    "A pope crowns Charlemagne emperor on Christmas Day.",
    800,
    41.9,
    12.46,
    "Rome, Italy",
    "Imperial politics",
    4,
  ],
  [
    "Al-Khwarizmi writes his treatise on algebra.",
    820,
    33.34,
    44.4,
    "Baghdad, Iraq",
    "Mathematics",
    2,
    { timeScale: 40 },
  ],
  [
    "Norse voyagers settle at L’Anse aux Meadows.",
    1000,
    51.6,
    -55.53,
    "Newfoundland",
    "Exploration",
    2,
    { timeScale: 40 },
  ],
  [
    "Murasaki Shikibu writes The Tale of Genji.",
    1010,
    35.01,
    135.77,
    "Kyoto, Japan",
    "Literature",
    3,
    { timeScale: 40 },
  ],
  [
    "The Great Schism divides the Eastern and Western churches.",
    1054,
    41.01,
    28.98,
    "Constantinople",
    "Religious history",
    3,
  ],
  [
    "William of Normandy defeats and kills the English king Harold.",
    1066,
    50.91,
    0.49,
    "Hastings, England",
    "Military history",
    5,
  ],
  [
    "A pope calls on Christendom to march east and retake Jerusalem.",
    1095,
    45.78,
    3.08,
    "Clermont, France",
    "Religious history",
    4,
  ],
  [
    "Crusaders storm the holy city after a five-week siege.",
    1099,
    31.78,
    35.23,
    "Jerusalem",
    "Military history",
    3,
  ],
  [
    "A Khmer king begins what will become the largest religious monument on earth.",
    1113,
    13.41,
    103.87,
    "Angkor, Cambodia",
    "Architecture",
    3,
    { timeScale: 40 },
  ],
  [
    "Genghis Khan is proclaimed ruler of all the Mongols.",
    1206,
    48.4,
    108.7,
    "Onon River, Mongolia",
    "State formation",
    4,
  ],
  [
    "Mongol armies destroy the Abbasid capital and throw its libraries into the river.",
    1258,
    33.34,
    44.4,
    "Baghdad, Iraq",
    "Military history",
    3,
  ],
  [
    "Marco Polo arrives at the court of Kublai Khan.",
    1275,
    42.36,
    116.18,
    "Shangdu, China",
    "Exploration",
    2,
  ],
  [
    "Dante completes the Divine Comedy.",
    1320,
    44.42,
    12.2,
    "Ravenna, Italy",
    "Literature",
    3,
  ],
  [
    "The Mexica found a city on an island in a highland lake.",
    1325,
    19.43,
    -99.13,
    "Tenochtitlan, Mexico",
    "Dynastic history",
    2,
    { timeScale: 40 },
  ],
  [
    "A young Moroccan jurist sets out on travels that will cross much of the known world.",
    1325,
    35.77,
    -5.8,
    "Tangier, Morocco",
    "Exploration",
    2,
  ],
  [
    "The Black Death arrives in Sicily.",
    1347,
    38.19,
    15.55,
    "Messina, Sicily",
    "Epidemics",
    4,
  ],
  [
    "The Ming dynasty is founded.",
    1368,
    32.06,
    118.8,
    "Nanjing, China",
    "Dynastic history",
    3,
  ],
  [
    "Chaucer begins The Canterbury Tales.",
    1387,
    51.51,
    -0.12,
    "London, England",
    "Literature",
    2,
    { timeScale: 30 },
  ],
  [
    "Zheng He’s first treasure fleet sets sail.",
    1405,
    32.06,
    118.8,
    "Nanjing, China",
    "Exploration",
    3,
  ],
  [
    "English longbowmen destroy a far larger French army in the mud.",
    1415,
    50.46,
    2.14,
    "Agincourt, France",
    "Military history",
    3,
  ],
  [
    "The Forbidden City is completed.",
    1420,
    39.92,
    116.39,
    "Beijing, China",
    "Architecture",
    3,
  ],
  [
    "Joan of Arc is burned at the stake.",
    1431,
    49.44,
    1.1,
    "Rouen, France",
    "Medieval history",
    3,
  ],
  // ── Early modern ─────────────────────────────────────────────────────────
  [
    "Columbus makes his first landfall in the Americas.",
    1492,
    24.1,
    -74.5,
    "The Bahamas",
    "Exploration",
    5,
  ],
  [
    "Vasco da Gama completes the first sea route from Europe to India.",
    1498,
    11.25,
    75.78,
    "Calicut, India",
    "Exploration",
    4,
  ],
  [
    "Leonardo begins the Mona Lisa.",
    1503,
    43.77,
    11.26,
    "Florence, Italy",
    "Art",
    3,
    { timeScale: 25 },
  ],
  [
    "Michelangelo unveils his David.",
    1504,
    43.77,
    11.26,
    "Florence, Italy",
    "Art",
    3,
  ],
  [
    "Machiavelli writes The Prince.",
    1513,
    43.77,
    11.25,
    "Florence, Italy",
    "Political thought",
    3,
  ],
  [
    "Martin Luther circulates the Ninety-five Theses.",
    1517,
    51.87,
    12.65,
    "Wittenberg, Germany",
    "Reformation",
    5,
  ],
  [
    "The Victoria completes the first circumnavigation of the globe.",
    1522,
    36.53,
    -6.29,
    "Sanlúcar de Barrameda, Spain",
    "Exploration",
    3,
  ],
  [
    "Calvin publishes the Institutes of the Christian Religion.",
    1536,
    47.56,
    7.59,
    "Basel, Switzerland",
    "Reformation",
    2,
  ],
  [
    "Copernicus’s argument for a sun-centred cosmos goes to press.",
    1543,
    49.45,
    11.08,
    "Nuremberg, Germany",
    "Astronomy",
    4,
  ],
  [
    "Mercator publishes his world map projection.",
    1569,
    51.43,
    6.76,
    "Duisburg, Germany",
    "Cartography",
    2,
  ],
  [
    "The Holy League defeats the Ottoman fleet at Lepanto.",
    1571,
    38.24,
    21.32,
    "Gulf of Patras, Greece",
    "Naval history",
    3,
  ],
  [
    "The Spanish Armada is defeated.",
    1588,
    50.2,
    -4.1,
    "English Channel",
    "Naval history",
    4,
  ],
  [
    "Hamlet is first performed.",
    1601,
    51.51,
    -0.1,
    "London, England",
    "Theater",
    4,
    { timeScale: 15 },
  ],
  [
    "The Dutch East India Company is chartered.",
    1602,
    52.37,
    4.9,
    "Amsterdam, Netherlands",
    "Trade",
    3,
  ],
  [
    "Cervantes publishes Don Quixote.",
    1605,
    40.42,
    -3.7,
    "Madrid, Spain",
    "Literature",
    4,
  ],
  [
    "English colonists plant their first lasting settlement in North America.",
    1607,
    37.21,
    -76.78,
    "Jamestown, Virginia",
    "Colonial history",
    4,
  ],
  [
    "Galileo turns his telescope on the heavens.",
    1609,
    45.41,
    11.88,
    "Padua, Italy",
    "Astronomy",
    4,
  ],
  [
    "Bohemian nobles throw imperial officials from a castle window, igniting a thirty-year war.",
    1618,
    50.09,
    14.4,
    "Prague, Bohemia",
    "Military history",
    3,
  ],
  [
    "The Mayflower’s passengers land after a sixty-six-day crossing.",
    1620,
    41.96,
    -70.66,
    "Plymouth, Massachusetts",
    "Migration",
    4,
  ],
  [
    "Galileo is tried by the Inquisition.",
    1633,
    41.9,
    12.46,
    "Rome, Italy",
    "Science",
    3,
  ],
  [
    "Descartes publishes the Discourse on the Method.",
    1637,
    52.16,
    4.49,
    "Leiden, Netherlands",
    "Philosophy",
    3,
  ],
  [
    "Tulip mania collapses.",
    1637,
    52.38,
    4.64,
    "Haarlem, Netherlands",
    "Economic history",
    2,
  ],
  [
    "Rembrandt paints The Night Watch.",
    1642,
    52.37,
    4.89,
    "Amsterdam, Netherlands",
    "Art",
    2,
  ],
  [
    "The Peace of Westphalia ends the Thirty Years’ War.",
    1648,
    51.96,
    7.63,
    "Münster, Germany",
    "Diplomacy",
    4,
  ],
  [
    "Hobbes publishes Leviathan.",
    1651,
    51.51,
    -0.12,
    "London, England",
    "Political thought",
    2,
  ],
  [
    "The Taj Mahal is completed.",
    1653,
    27.17,
    78.04,
    "Agra, India",
    "Architecture",
    4,
  ],
  [
    "A bakery fire destroys most of a great European capital.",
    1666,
    51.51,
    -0.09,
    "London, England",
    "Disaster",
    4,
  ],
  [
    "A Polish-led relief army breaks an Ottoman siege of a Habsburg capital.",
    1683,
    48.21,
    16.37,
    "Vienna, Austria",
    "Military history",
    3,
  ],
  [
    "Newton publishes the Principia.",
    1687,
    51.51,
    -0.12,
    "London, England",
    "Physics",
    5,
  ],
  [
    "The Bank of England is founded.",
    1694,
    51.51,
    -0.09,
    "London, England",
    "Economic history",
    3,
  ],
  [
    "A tsar founds a new capital on marshland to face westward.",
    1703,
    59.94,
    30.31,
    "Saint Petersburg, Russia",
    "State formation",
    3,
  ],
  [
    "The South Sea Bubble bursts.",
    1720,
    51.51,
    -0.09,
    "London, England",
    "Economic history",
    2,
  ],
  [
    "Bach’s St Matthew Passion is first performed.",
    1727,
    51.34,
    12.37,
    "Leipzig, Germany",
    "Music",
    2,
  ],
  [
    "An earthquake, fire and tsunami wreck a European capital on All Saints’ Day.",
    1755,
    38.72,
    -9.14,
    "Lisbon, Portugal",
    "Disaster",
    3,
  ],
  [
    "A British company victory hands its shareholders the revenues of Bengal.",
    1757,
    23.8,
    88.25,
    "Plassey, Bengal",
    "Colonial history",
    3,
  ],
  [
    "Rousseau publishes The Social Contract.",
    1762,
    52.37,
    4.9,
    "Amsterdam, Netherlands",
    "Political thought",
    2,
  ],
  [
    "James Watt patents his improved steam engine.",
    1769,
    55.86,
    -4.25,
    "Glasgow, Scotland",
    "Technology",
    4,
  ],
  [
    "Captain Cook makes his first landing on the east coast of a southern continent.",
    1770,
    -34.0,
    151.22,
    "Botany Bay, Australia",
    "Exploration",
    3,
  ],
  // ── Age of revolutions ───────────────────────────────────────────────────
  [
    "The Declaration of Independence is adopted.",
    1776,
    39.95,
    -75.15,
    "Philadelphia, USA",
    "Revolution",
    5,
  ],
  [
    "Adam Smith publishes The Wealth of Nations.",
    1776,
    51.51,
    -0.12,
    "London, England",
    "Economic history",
    4,
  ],
  [
    "Lavoisier names oxygen.",
    1777,
    48.86,
    2.35,
    "Paris, France",
    "Chemistry",
    2,
  ],
  [
    "Kant publishes the Critique of Pure Reason.",
    1781,
    54.71,
    20.51,
    "Königsberg, Prussia",
    "Philosophy",
    3,
  ],
  [
    "The United States Constitution is signed.",
    1787,
    39.95,
    -75.15,
    "Philadelphia, USA",
    "Constitutional history",
    5,
  ],
  [
    "Mozart’s Don Giovanni premieres.",
    1787,
    50.09,
    14.42,
    "Prague, Bohemia",
    "Music",
    3,
  ],
  [
    "A crowd storms a royal fortress and prison.",
    1789,
    48.85,
    2.37,
    "Paris, France",
    "Revolution",
    5,
  ],
  [
    "Volta announces the electric battery.",
    1800,
    45.81,
    9.08,
    "Como, Italy",
    "Science",
    2,
  ],
  [
    "The Louisiana Purchase treaty is signed.",
    1803,
    48.86,
    2.34,
    "Paris, France",
    "Diplomacy",
    3,
  ],
  [
    "The Napoleonic Code comes into force.",
    1804,
    48.86,
    2.35,
    "Paris, France",
    "Legal history",
    3,
  ],
  [
    "Nelson destroys a combined French and Spanish fleet and is killed in the battle.",
    1805,
    36.25,
    -6.2,
    "Cape Trafalgar, Spain",
    "Naval history",
    4,
  ],
  [
    "The Brothers Grimm publish their fairy tales.",
    1812,
    51.32,
    9.5,
    "Kassel, Germany",
    "Literature",
    2,
  ],
  [
    "Napoleon suffers his final defeat and abdicates for the second time.",
    1815,
    50.68,
    4.41,
    "Waterloo, Belgium",
    "Military history",
    5,
  ],
  [
    "Mount Tambora erupts, bringing the ‘year without a summer’.",
    1815,
    -8.25,
    118.0,
    "Sumbawa, Indonesia",
    "Disaster",
    2,
  ],
  [
    "The victorious powers convene to redraw the map of Europe after Napoleon.",
    1815,
    48.21,
    16.37,
    "Vienna, Austria",
    "Diplomacy",
    3,
  ],
  [
    "Bolívar’s victory secures the independence of New Granada.",
    1819,
    5.45,
    -73.42,
    "Boyacá, Colombia",
    "Revolution",
    3,
  ],
  [
    "Champollion announces he has deciphered hieroglyphs.",
    1822,
    48.85,
    2.34,
    "Paris, France",
    "Linguistics",
    3,
  ],
  [
    "Beethoven’s Ninth Symphony premieres.",
    1824,
    48.21,
    16.37,
    "Vienna, Austria",
    "Music",
    4,
  ],
  [
    "The Erie Canal opens.",
    1825,
    42.65,
    -73.75,
    "Albany, New York",
    "Infrastructure",
    2,
  ],
  [
    "Niépce makes the earliest surviving photograph.",
    1826,
    46.75,
    4.85,
    "Saint-Loup-de-Varennes, France",
    "Technology",
    2,
    { timeScale: 8 },
  ],
  [
    "Britain abolishes slavery throughout its empire.",
    1833,
    51.5,
    -0.12,
    "London, England",
    "Legal history",
    4,
  ],
  [
    "Darwin’s survey ship reaches an equatorial volcanic archipelago.",
    1835,
    -0.83,
    -91.13,
    "Galápagos Islands",
    "Science",
    3,
  ],
  [
    "Morse sends the first telegraph message between cities.",
    1844,
    38.89,
    -77.01,
    "Washington, USA",
    "Communications",
    3,
  ],
  [
    "Potato blight triggers the Great Famine in Ireland.",
    1845,
    51.55,
    -9.27,
    "Skibbereen, Ireland",
    "Disaster",
    3,
  ],
  [
    "Ether anesthesia is demonstrated publicly.",
    1846,
    42.36,
    -71.07,
    "Boston, USA",
    "Medicine",
    2,
  ],
  [
    "Marx and Engels publish the Communist Manifesto.",
    1848,
    51.51,
    -0.12,
    "London, England",
    "Political thought",
    4,
  ],
  [
    "Revolution topples the July Monarchy and proclaims a second republic.",
    1848,
    48.86,
    2.35,
    "Paris, France",
    "Revolution",
    3,
  ],
  [
    "The first women’s rights convention issues a declaration of sentiments.",
    1848,
    42.91,
    -76.8,
    "Seneca Falls, New York",
    "Women’s history",
    3,
  ],
  [
    "The Great Exhibition opens in the Crystal Palace.",
    1851,
    51.5,
    -0.17,
    "London, England",
    "Technology",
    2,
  ],
  [
    "John Snow traces cholera to the Broad Street pump.",
    1854,
    51.51,
    -0.14,
    "London, England",
    "Medicine",
    2,
  ],
  [
    "A British light cavalry brigade charges the wrong guns.",
    1854,
    44.5,
    33.6,
    "Balaclava, Crimea",
    "Military history",
    2,
  ],
  [
    "Bessemer patents his steel-making process.",
    1856,
    53.38,
    -1.47,
    "Sheffield, England",
    "Technology",
    2,
  ],
  [
    "The first transatlantic telegraph cable is completed.",
    1858,
    47.6,
    -52.7,
    "Newfoundland",
    "Communications",
    2,
  ],
  [
    "Darwin publishes On the Origin of Species.",
    1859,
    51.51,
    -0.12,
    "London, England",
    "Science",
    5,
  ],
  [
    "The Kingdom of Italy is proclaimed.",
    1861,
    45.07,
    7.69,
    "Turin, Italy",
    "State formation",
    3,
  ],
  [
    "Lincoln issues the Emancipation Proclamation.",
    1863,
    38.9,
    -77.04,
    "Washington, USA",
    "Civil rights",
    4,
  ],
  [
    "Union forces turn back Lee’s invasion of the North.",
    1863,
    39.81,
    -77.23,
    "Gettysburg, USA",
    "Military history",
    4,
  ],
  [
    "Abraham Lincoln is assassinated.",
    1865,
    38.9,
    -77.03,
    "Washington, USA",
    "Political history",
    4,
  ],
  [
    "Mendel presents his experiments on pea plants.",
    1865,
    49.2,
    16.61,
    "Brno, Moravia",
    "Biology",
    2,
  ],
  [
    "Tolstoy completes War and Peace.",
    1869,
    55.75,
    37.62,
    "Moscow, Russia",
    "Literature",
    3,
  ],
  [
    "The Suez Canal opens.",
    1869,
    30.59,
    32.27,
    "Port Said, Egypt",
    "Infrastructure",
    4,
  ],
  [
    "A golden spike joins the first American transcontinental railroad.",
    1869,
    41.62,
    -112.55,
    "Promontory, Utah",
    "Infrastructure",
    3,
  ],
  [
    "Mendeleev publishes the periodic table.",
    1869,
    59.94,
    30.31,
    "Saint Petersburg, Russia",
    "Chemistry",
    3,
  ],
  [
    "The German Empire is proclaimed in a palace hall of mirrors.",
    1871,
    48.8,
    2.12,
    "Versailles, France",
    "State formation",
    4,
  ],
  [
    "A journalist finds the missing missionary explorer beside a great lake.",
    1871,
    -4.91,
    29.67,
    "Ujiji, Tanzania",
    "Exploration",
    2,
  ],
  [
    "Schliemann begins excavating Troy.",
    1871,
    39.96,
    26.24,
    "Hisarlik, Turkey",
    "Archaeology",
    2,
  ],
  [
    "Bell is granted a patent for the telephone.",
    1876,
    42.36,
    -71.06,
    "Boston, USA",
    "Communications",
    3,
  ],
  [
    "Edison demonstrates a practical incandescent lamp.",
    1879,
    40.53,
    -74.41,
    "Menlo Park, New Jersey",
    "Technology",
    3,
  ],
  [
    "A volcanic island explodes, and the sound is heard thousands of miles away.",
    1883,
    -6.1,
    105.42,
    "Krakatoa, Indonesia",
    "Disaster",
    3,
  ],
  [
    "The Brooklyn Bridge opens.",
    1883,
    40.71,
    -73.99,
    "New York, USA",
    "Engineering",
    2,
  ],
  [
    "The first fascicle of a monumental English dictionary is published.",
    1884,
    51.75,
    -1.26,
    "Oxford, England",
    "Linguistics",
    2,
  ],
  [
    "Pasteur administers the first rabies vaccine.",
    1885,
    48.84,
    2.34,
    "Paris, France",
    "Medicine",
    3,
  ],
  [
    "A bomb thrown at a labour rally leads to a notorious trial of anarchists.",
    1886,
    41.88,
    -87.64,
    "Chicago, USA",
    "Labor history",
    2,
  ],
  [
    "Zamenhof publishes the first book in Esperanto.",
    1887,
    52.23,
    21.01,
    "Warsaw, Poland",
    "Linguistics",
    1,
  ],
  [
    "The Eiffel Tower is completed.",
    1889,
    48.86,
    2.29,
    "Paris, France",
    "Architecture",
    4,
  ],
  [
    "New Zealand grants women the vote.",
    1893,
    -41.29,
    174.78,
    "Wellington, New Zealand",
    "Women’s history",
    3,
  ],
  [
    "Alfred Dreyfus is convicted of treason.",
    1894,
    48.85,
    2.32,
    "Paris, France",
    "Legal history",
    2,
  ],
  [
    "Röntgen discovers X-rays.",
    1895,
    49.79,
    9.94,
    "Würzburg, Germany",
    "Physics",
    3,
  ],
  [
    "The Lumière brothers hold the first public film screening.",
    1895,
    48.87,
    2.33,
    "Paris, France",
    "Film",
    3,
  ],
  [
    "An Ethiopian army destroys an Italian invasion force.",
    1896,
    14.16,
    38.9,
    "Adwa, Ethiopia",
    "Colonial history",
    3,
  ],
  [
    "The Curies announce the discovery of radium.",
    1898,
    48.84,
    2.35,
    "Paris, France",
    "Chemistry",
    3,
  ],
  // ── Twentieth century ────────────────────────────────────────────────────
  [
    "The Boxer Rebellion besieges the foreign legations.",
    1900,
    39.9,
    116.4,
    "Beijing, China",
    "Colonial history",
    2,
  ],
  [
    "Marconi receives the first transatlantic wireless signal.",
    1901,
    47.57,
    -52.7,
    "St John’s, Newfoundland",
    "Communications",
    3,
  ],
  [
    "Einstein publishes the special theory of relativity.",
    1905,
    46.95,
    7.45,
    "Bern, Switzerland",
    "Physics",
    4,
  ],
  [
    "A Japanese fleet annihilates a Russian squadron that had sailed halfway round the world.",
    1905,
    34.5,
    129.6,
    "Tsushima Strait",
    "Naval history",
    3,
  ],
  [
    "An earthquake and the fires that follow gut a major Pacific-coast city.",
    1906,
    37.77,
    -122.42,
    "San Francisco, USA",
    "Disaster",
    3,
  ],
  [
    "Ford introduces the Model T.",
    1908,
    42.33,
    -83.05,
    "Detroit, USA",
    "Technology",
    3,
  ],
  [
    "A Norwegian expedition becomes the first to reach Earth’s southernmost point.",
    1911,
    -89.9,
    0,
    "South Pole",
    "Exploration",
    3,
  ],
  [
    "The Triangle Shirtwaist Factory burns.",
    1911,
    40.73,
    -73.99,
    "New York, USA",
    "Labor history",
    2,
  ],
  ["The Titanic sinks.", 1912, 41.73, -49.95, "North Atlantic", "Disaster", 4],
  [
    "Stravinsky’s Rite of Spring causes a riot at its premiere.",
    1913,
    48.87,
    2.31,
    "Paris, France",
    "Music",
    3,
  ],
  [
    "Archduke Franz Ferdinand is assassinated.",
    1914,
    43.86,
    18.43,
    "Sarajevo, Bosnia",
    "Geopolitics",
    5,
  ],
  [
    "Republicans seize a post office and proclaim an Irish republic.",
    1916,
    53.35,
    -6.26,
    "Dublin, Ireland",
    "Revolution",
    3,
  ],
  [
    "Bolsheviks storm the Winter Palace.",
    1917,
    59.94,
    30.31,
    "Petrograd, Russia",
    "Revolution",
    5,
  ],
  [
    "The treaty imposing reparations and war guilt on Germany is signed.",
    1919,
    48.8,
    2.12,
    "Versailles, France",
    "Diplomacy",
    4,
  ],
  [
    "Prohibition takes effect in the United States.",
    1920,
    38.9,
    -77.04,
    "Washington, USA",
    "Social history",
    3,
  ],
  [
    "The Nineteenth Amendment is ratified.",
    1920,
    36.17,
    -86.78,
    "Nashville, USA",
    "Women’s history",
    3,
  ],
  [
    "KDKA makes the first scheduled commercial radio broadcast.",
    1920,
    40.44,
    -79.99,
    "Pittsburgh, USA",
    "Communications",
    2,
  ],
  [
    "Carter opens the tomb of Tutankhamun.",
    1922,
    25.74,
    32.6,
    "Valley of the Kings, Egypt",
    "Archaeology",
    3,
  ],
  [
    "Joyce’s Ulysses is published in full for the first time.",
    1922,
    48.85,
    2.34,
    "Paris, France",
    "Literature",
    2,
  ],
  [
    "Lindbergh lands at Le Bourget after crossing the Atlantic.",
    1927,
    48.97,
    2.44,
    "Paris, France",
    "Aviation",
    3,
  ],
  [
    "The Jazz Singer ushers in talking pictures.",
    1927,
    40.76,
    -73.98,
    "New York, USA",
    "Film",
    2,
  ],
  [
    "Fleming discovers penicillin.",
    1928,
    51.52,
    -0.17,
    "London, England",
    "Medicine",
    4,
  ],
  [
    "Wall Street crashes.",
    1929,
    40.71,
    -74.01,
    "New York, USA",
    "Economic history",
    5,
  ],
  [
    "Gandhi reaches the sea and makes salt in defiance of a British monopoly.",
    1930,
    20.92,
    72.83,
    "Dandi, India",
    "Decolonization",
    4,
  ],
  [
    "Gödel publishes his incompleteness theorems.",
    1931,
    48.21,
    16.37,
    "Vienna, Austria",
    "Mathematics",
    2,
  ],
  [
    "Hitler is appointed Chancellor of Germany.",
    1933,
    52.52,
    13.38,
    "Berlin, Germany",
    "Political history",
    4,
  ],
  [
    "The Hoover Dam is completed.",
    1936,
    36.02,
    -114.74,
    "Nevada–Arizona border",
    "Engineering",
    2,
  ],
  [
    "The BBC begins regular television broadcasts.",
    1936,
    51.58,
    -0.13,
    "Alexandra Palace, London",
    "Communications",
    2,
  ],
  [
    "German and Italian aircraft bomb a Basque market town.",
    1937,
    43.31,
    -2.68,
    "Guernica, Spain",
    "Military history",
    3,
  ],
  [
    "Picasso’s mural of an aerial bombing is unveiled at a world’s fair.",
    1937,
    48.86,
    2.29,
    "Paris, France",
    "Art",
    3,
  ],
  [
    "A German airship bursts into flames while mooring.",
    1937,
    40.03,
    -74.35,
    "Lakehurst, New Jersey",
    "Aviation",
    2,
  ],
  [
    "The Golden Gate Bridge opens.",
    1937,
    37.82,
    -122.48,
    "San Francisco, USA",
    "Engineering",
    2,
  ],
  [
    "Lascaux’s painted caves are discovered.",
    1940,
    45.05,
    1.17,
    "Montignac, France",
    "Archaeology",
    2,
  ],
  [
    "Delegates from forty-four nations fix a postwar monetary order at a mountain resort.",
    1944,
    44.26,
    -71.44,
    "Bretton Woods, New Hampshire",
    "Economic history",
    3,
  ],
  [
    "Roosevelt, Churchill and Stalin meet at a seaside palace to divide postwar Europe.",
    1945,
    44.47,
    34.14,
    "Yalta, Crimea",
    "Diplomacy",
    3,
  ],
  [
    "The first atomic bomb used in war is dropped on a city.",
    1945,
    34.39,
    132.45,
    "Hiroshima, Japan",
    "Military history",
    5,
  ],
  [
    "The United Nations Charter is signed.",
    1945,
    37.78,
    -122.42,
    "San Francisco, USA",
    "Diplomacy",
    4,
  ],
  [
    "An international tribunal opens the trial of surviving Nazi leaders.",
    1945,
    49.45,
    11.05,
    "Nuremberg, Germany",
    "Legal history",
    3,
  ],
  [
    "ENIAC is unveiled to the public.",
    1946,
    39.95,
    -75.19,
    "Philadelphia, USA",
    "Computing",
    3,
  ],
  [
    "The transistor is invented at Bell Labs.",
    1947,
    40.68,
    -74.4,
    "Murray Hill, New Jersey",
    "Computing",
    3,
  ],
  [
    "A shepherd finds ancient scrolls in desert caves above a salt sea.",
    1947,
    31.74,
    35.46,
    "Qumran, West Bank",
    "Archaeology",
    2,
  ],
  [
    "Israel declares independence.",
    1948,
    32.07,
    34.78,
    "Tel Aviv",
    "State formation",
    4,
  ],
  [
    "Allied aircraft begin supplying a blockaded city entirely by air.",
    1948,
    52.47,
    13.4,
    "Berlin, Germany",
    "Geopolitics",
    3,
  ],
  [
    "Mao proclaims the People’s Republic of China.",
    1949,
    39.9,
    116.39,
    "Beijing, China",
    "State formation",
    5,
  ],
  [
    "Hillary and Tenzing reach the summit of the world’s highest mountain.",
    1953,
    27.99,
    86.93,
    "Mount Everest",
    "Exploration",
    4,
  ],
  [
    "The Supreme Court decides Brown v. Board of Education.",
    1954,
    38.89,
    -77.0,
    "Washington, USA",
    "Civil rights",
    3,
  ],
  [
    "The Salk polio vaccine is declared safe and effective.",
    1955,
    42.28,
    -83.74,
    "Ann Arbor, USA",
    "Medicine",
    3,
  ],
  [
    "Rosa Parks refuses to give up her bus seat.",
    1955,
    32.38,
    -86.31,
    "Montgomery, USA",
    "Civil rights",
    4,
  ],
  [
    "Ghana becomes independent.",
    1957,
    5.6,
    -0.19,
    "Accra, Ghana",
    "Decolonization",
    3,
  ],
  [
    "Six nations sign the treaty founding the European Economic Community.",
    1957,
    41.89,
    12.48,
    "Rome, Italy",
    "Diplomacy",
    3,
  ],
  [
    "Sputnik 1 is launched.",
    1957,
    45.92,
    63.34,
    "Baikonur, Kazakhstan",
    "Space exploration",
    5,
  ],
  [
    "OPEC is founded.",
    1960,
    33.32,
    44.37,
    "Baghdad, Iraq",
    "Economic history",
    2,
  ],
  [
    "Yuri Gagarin becomes the first human in space.",
    1961,
    45.92,
    63.34,
    "Baikonur, Kazakhstan",
    "Space exploration",
    4,
  ],
  [
    "Overnight, barbed wire and concrete seal a divided city in two.",
    1961,
    52.52,
    13.4,
    "Berlin, Germany",
    "Geopolitics",
    5,
  ],
  [
    "The Cuban Missile Crisis brings the superpowers to the brink.",
    1962,
    23.11,
    -82.37,
    "Havana, Cuba",
    "Geopolitics",
    4,
  ],
  [
    "Martin Luther King Jr. delivers ‘I Have a Dream’.",
    1963,
    38.89,
    -77.05,
    "Washington, USA",
    "Civil rights",
    4,
  ],
  [
    "The Beatles play Shea Stadium.",
    1965,
    40.76,
    -73.85,
    "New York, USA",
    "Music",
    2,
  ],
  [
    "Christiaan Barnard performs the first human heart transplant.",
    1967,
    -33.94,
    18.46,
    "Cape Town, South Africa",
    "Medicine",
    3,
  ],
  [
    "One Hundred Years of Solitude is published.",
    1967,
    -34.6,
    -58.38,
    "Buenos Aires, Argentina",
    "Literature",
    2,
  ],
  [
    "Apollo 11 lifts off for the Moon.",
    1969,
    28.57,
    -80.65,
    "Cape Kennedy, Florida",
    "Space exploration",
    5,
  ],
  [
    "The Stonewall uprising begins.",
    1969,
    40.73,
    -74.0,
    "New York, USA",
    "Civil rights",
    3,
  ],
  [
    "Concorde makes its maiden flight.",
    1969,
    43.63,
    1.37,
    "Toulouse, France",
    "Aviation",
    2,
  ],
  [
    "Woodstock opens on a dairy farm.",
    1969,
    41.7,
    -74.88,
    "Bethel, New York",
    "Music",
    2,
  ],
  [
    "Bangladesh declares independence.",
    1971,
    23.81,
    90.41,
    "Dhaka, Bangladesh",
    "Decolonization",
    2,
  ],
  [
    "Farmers unearth the Terracotta Army.",
    1974,
    34.38,
    109.28,
    "Xi’an, China",
    "Archaeology",
    3,
  ],
  [
    "The southern capital falls and helicopters lift the last evacuees from an embassy roof.",
    1975,
    10.78,
    106.7,
    "Saigon, Vietnam",
    "Military history",
    4,
  ],
  [
    "Voyager 1 is launched.",
    1977,
    28.57,
    -80.65,
    "Cape Canaveral, Florida",
    "Space exploration",
    2,
  ],
  [
    "Egypt and Israel agree a framework for peace at an American presidential retreat.",
    1978,
    39.65,
    -77.47,
    "Camp David, Maryland",
    "Diplomacy",
    2,
  ],
  ["The Shah flees Iran.", 1979, 35.69, 51.39, "Tehran, Iran", "Revolution", 4],
  [
    "Solidarity is born in the Gdańsk shipyard.",
    1980,
    54.36,
    18.65,
    "Gdańsk, Poland",
    "Labor history",
    3,
  ],
  [
    "The Challenger breaks apart after launch.",
    1986,
    28.57,
    -80.65,
    "Cape Canaveral, Florida",
    "Space exploration",
    3,
  ],
  [
    "A reactor explodes during a safety test and scatters fallout across Europe.",
    1986,
    51.39,
    30.1,
    "Chernobyl, Ukraine",
    "Disaster",
    4,
  ],
  [
    "Tim Berners-Lee proposes the World Wide Web.",
    1989,
    46.23,
    6.05,
    "CERN, Geneva",
    "Computing",
    4,
  ],
  [
    "Tanks clear protesters from Tiananmen Square.",
    1989,
    39.9,
    116.39,
    "Beijing, China",
    "Political history",
    4,
  ],
  [
    "Crowds breach a wall dividing a city, and the guards stand aside.",
    1989,
    52.52,
    13.4,
    "Berlin, Germany",
    "Geopolitics",
    5,
  ],
  [
    "Nelson Mandela walks free.",
    1990,
    -33.79,
    18.97,
    "Paarl, South Africa",
    "Civil rights",
    4,
  ],
  [
    "The Hubble Space Telescope is launched.",
    1990,
    28.57,
    -80.65,
    "Cape Canaveral, Florida",
    "Space exploration",
    3,
  ],
  [
    "The Soviet Union is dissolved.",
    1991,
    55.75,
    37.62,
    "Moscow, Russia",
    "Geopolitics",
    5,
  ],
  [
    "Andrew Wiles announces a proof of Fermat’s Last Theorem.",
    1993,
    52.21,
    0.12,
    "Cambridge, England",
    "Mathematics",
    2,
  ],
  [
    "The Rwandan genocide begins.",
    1994,
    -1.95,
    30.06,
    "Kigali, Rwanda",
    "Human rights",
    3,
  ],
  [
    "The Channel Tunnel opens.",
    1994,
    51.1,
    1.15,
    "Folkestone, England",
    "Engineering",
    2,
  ],
  [
    "Dolly the cloned sheep is announced.",
    1997,
    55.87,
    -3.2,
    "Roslin, Scotland",
    "Science",
    2,
  ],
  [
    "Britain hands its last major Asian colony back to China.",
    1997,
    22.28,
    114.16,
    "Hong Kong",
    "Decolonization",
    3,
  ],
  [
    "The Good Friday Agreement is signed.",
    1998,
    54.6,
    -5.93,
    "Belfast, Northern Ireland",
    "Diplomacy",
    2,
  ],
  [
    "The first module of the International Space Station is launched.",
    1998,
    45.92,
    63.34,
    "Baikonur, Kazakhstan",
    "Space exploration",
    2,
  ],
  // ── Twenty-first century ─────────────────────────────────────────────────
  [
    "Hijacked planes strike the World Trade Center.",
    2001,
    40.71,
    -74.01,
    "New York, USA",
    "Geopolitics",
    5,
  ],
  [
    "Euro notes and coins enter circulation.",
    2002,
    50.11,
    8.68,
    "Frankfurt, Germany",
    "Economic history",
    2,
  ],
  [
    "A tsunami devastates coasts around the Indian Ocean.",
    2004,
    3.32,
    95.85,
    "off Sumatra, Indonesia",
    "Disaster",
    3,
  ],
  [
    "Apple unveils the iPhone.",
    2007,
    37.78,
    -122.4,
    "San Francisco, USA",
    "Technology",
    3,
  ],
  [
    "Lehman Brothers files for bankruptcy.",
    2008,
    40.76,
    -73.98,
    "New York, USA",
    "Economic history",
    4,
  ],
  [
    "A street vendor’s self-immolation sparks protests that topple a North African president.",
    2011,
    36.81,
    10.17,
    "Tunis, Tunisia",
    "Revolution",
    3,
  ],
  [
    "An earthquake and tsunami trigger meltdowns at a coastal nuclear plant.",
    2011,
    37.42,
    141.03,
    "Fukushima, Japan",
    "Disaster",
    3,
  ],
  [
    "The Three Gorges Dam reaches full operation.",
    2012,
    30.82,
    111.0,
    "Hubei, China",
    "Engineering",
    2,
  ],
];

export const EVENTS: Event[] = ROWS.map(
  ([title, year, lat, lon, place, field, weight, calibration]) => ({
    title,
    year,
    lat,
    lon,
    place,
    field,
    weight,
    ...FIELD_RULES[field],
    ...calibration,
  }),
);

const e = (
  title: string,
  year: number,
  lat: number,
  lon: number,
  place: string,
  field: string,
): Event => ({ title, year, lat, lon, place, field, weight: 3 });
export const FOCUSES: Focus[] = [
  {
    name: "The Second World War",
    note: "A global war, fifteen years close",
    years: [1931, 1946],
    view: { lat: 45, lon: 25, distance: 2.65 },
    deck: [
      e(
        "Germany invades Poland.",
        1939,
        52.23,
        21.01,
        "Warsaw, Poland",
        "European theater",
      ),
      e(
        "The evacuation from Dunkirk begins.",
        1940,
        51.04,
        2.38,
        "Dunkirk, France",
        "European theater",
      ),
      e(
        "Japan attacks Pearl Harbor.",
        1941,
        21.36,
        -157.95,
        "Oahu, Hawaii",
        "Pacific theater",
      ),
      e(
        "The Battle of Stalingrad ends.",
        1943,
        48.71,
        44.51,
        "Stalingrad",
        "Eastern Front",
      ),
      e(
        "Allied forces land in Normandy.",
        1944,
        49.34,
        -0.62,
        "Normandy, France",
        "European theater",
      ),
      e(
        "The first atomic bomb used in war is dropped on a city.",
        1945,
        34.39,
        132.45,
        "Hiroshima, Japan",
        "Pacific theater",
      ),
      e(
        "Japan formally surrenders aboard the USS Missouri.",
        1945,
        35.29,
        139.67,
        "Tokyo Bay",
        "Pacific theater",
      ),
    ],
  },
  {
    name: "Japanese history",
    note: "An archipelago across twelve centuries",
    years: [700, 1950],
    view: { lat: 37, lon: 138, distance: 2.05 },
    deck: [
      e(
        "The imperial capital moves to Heian-kyō.",
        794,
        35.01,
        135.77,
        "Kyoto, Japan",
        "Heian period",
      ),
      e(
        "The Kamakura shogunate is established.",
        1192,
        35.32,
        139.55,
        "Kamakura, Japan",
        "Kamakura period",
      ),
      e(
        "The Battle of Sekigahara establishes Tokugawa dominance.",
        1600,
        35.37,
        136.46,
        "Sekigahara, Japan",
        "Sengoku period",
      ),
      e(
        "The Tokugawa shogunate is established.",
        1603,
        35.68,
        139.76,
        "Edo, Japan",
        "Edo period",
      ),
      e(
        "Commodore Perry enters Edo Bay.",
        1853,
        35.24,
        139.72,
        "Uraga, Japan",
        "Bakumatsu",
      ),
      e(
        "The Meiji Restoration is proclaimed.",
        1868,
        35.68,
        139.76,
        "Tokyo, Japan",
        "Meiji period",
      ),
      e(
        "The Great Kantō earthquake strikes.",
        1923,
        35.44,
        139.64,
        "Kantō, Japan",
        "Social history",
      ),
    ],
  },
  {
    name: "The Scientific Revolution",
    note: "Observation changes the world",
    years: [1450, 1750],
    view: { lat: 49, lon: 11, distance: 2.3 },
    deck: [
      e(
        "Copernicus’s De revolutionibus is published.",
        1543,
        54.35,
        18.65,
        "Gdańsk, Poland",
        "Astronomy",
      ),
      e(
        "Tycho Brahe begins building Uraniborg.",
        1576,
        55.91,
        12.69,
        "Hven, Denmark",
        "Astronomy",
      ),
      e(
        "Galileo demonstrates his telescope in Venice.",
        1609,
        45.44,
        12.33,
        "Venice, Italy",
        "Astronomy",
      ),
      e(
        "William Harvey publishes his account of blood circulation.",
        1628,
        50.11,
        8.68,
        "Frankfurt, Germany",
        "Medicine",
      ),
      e(
        "The Royal Society is founded.",
        1660,
        51.51,
        -0.12,
        "London, England",
        "Institutions",
      ),
      e(
        "Newton’s Principia is published.",
        1687,
        51.51,
        -0.12,
        "London, England",
        "Physics",
      ),
      e(
        "Leeuwenhoek reports microorganisms.",
        1676,
        52.01,
        4.36,
        "Delft, Netherlands",
        "Microscopy",
      ),
    ],
  },
];
