import type { GlobePoint } from "./Globe";

export type Event = GlobePoint & {
  title: string;
  year: number;
  place: string;
  field: string;
  weight: number;
  years?: [number, number];
  spaceScale?: number;
  timeScale?: number;
};
export type Focus = {
  name: string;
  note: string;
  years: [number, number];
  view: GlobePoint & { distance: number };
  deck: Event[];
};
type Calibration = Partial<Pick<Event, "years" | "spaceScale" | "timeScale">>;
type Row = [
  title: string,
  year: number,
  lat: number,
  lon: number,
  place: string,
  field: string,
  weight: number,
  calibration?: Calibration,
];

export const PRESENT = 2026;

// Per-field calibration. `years` is the window the timeline exposes for the
// question; `spaceScale` (km) and `timeScale` (years) are the L2 normalisers.
// Fields not listed fall back to the full −4000..present window, an 1,800 km
// spatial scale, and an era-adjusted time scale. Individual events may
// override any of these.
export const FIELD_RULES: Record<string, Calibration> = {
  Baseball: { years: [1840, PRESENT], spaceScale: 500, timeScale: 10 },
  Football: { years: [1850, PRESENT], spaceScale: 900, timeScale: 8 },
  Olympics: { years: [1890, PRESENT], spaceScale: 900, timeScale: 6 },
  Athletics: { years: [1850, PRESENT], spaceScale: 800, timeScale: 8 },
  Boxing: { years: [1850, PRESENT], spaceScale: 900, timeScale: 8 },
  Hockey: { years: [1870, PRESENT], spaceScale: 700, timeScale: 8 },
  Tennis: { years: [1850, PRESENT], spaceScale: 600, timeScale: 10 },
  Cycling: { years: [1850, PRESENT], spaceScale: 600, timeScale: 10 },
  Sport: { years: [1700, PRESENT], spaceScale: 800, timeScale: 15 },
  Film: { years: [1880, PRESENT], spaceScale: 700, timeScale: 8 },
  Aviation: { years: [1780, PRESENT], spaceScale: 900, timeScale: 10 },
  "Space exploration": {
    years: [1940, PRESENT],
    spaceScale: 1500,
    timeScale: 5,
  },
  Computing: { years: [1820, PRESENT], spaceScale: 800, timeScale: 8 },
  Communications: { years: [1790, PRESENT], spaceScale: 1000, timeScale: 10 },
  Engineering: { years: [1700, PRESENT], spaceScale: 800, timeScale: 12 },
  Infrastructure: { years: [1700, PRESENT], spaceScale: 800, timeScale: 12 },
  Archaeology: { years: [1700, PRESENT], spaceScale: 1200, timeScale: 12 },
  "Civil rights": { years: [1750, PRESENT], spaceScale: 800, timeScale: 10 },
  "Labor history": { years: [1750, PRESENT], spaceScale: 800, timeScale: 10 },
  "Women’s history": {
    years: [1750, PRESENT],
    spaceScale: 1000,
    timeScale: 10,
  },
  Decolonization: { years: [1750, PRESENT], spaceScale: 1200, timeScale: 8 },
  Medicine: { years: [1500, PRESENT], spaceScale: 900, timeScale: 15 },
  Chemistry: { years: [1600, PRESENT], spaceScale: 900, timeScale: 15 },
  Physics: { years: [1500, PRESENT], spaceScale: 900, timeScale: 15 },
  Biology: { years: [1500, PRESENT], spaceScale: 900, timeScale: 15 },
  "Ancient history": { years: [-3500, 500], spaceScale: 2400, timeScale: 100 },
  "Classical antiquity": {
    years: [-1000, 600],
    spaceScale: 2200,
    timeScale: 70,
  },
  "Writing systems": {
    years: [-4000, -2000],
    spaceScale: 3000,
    timeScale: 220,
  },
  "Medieval history": { years: [500, 1500], spaceScale: 1700, timeScale: 50 },
  Architecture: { years: [-3000, PRESENT], spaceScale: 1600, timeScale: 50 },
  Art: { years: [1400, PRESENT], spaceScale: 1000, timeScale: 30 },
  Astronomy: { years: [1400, PRESENT], spaceScale: 1200, timeScale: 30 },
  Cartography: { years: [-1000, PRESENT], spaceScale: 1800, timeScale: 60 },
  "Colonial history": {
    years: [1450, PRESENT],
    spaceScale: 1800,
    timeScale: 30,
  },
  "Constitutional history": {
    years: [1100, PRESENT],
    spaceScale: 1100,
    timeScale: 20,
  },
  Diplomacy: { years: [1400, PRESENT], spaceScale: 1200, timeScale: 25 },
  Disaster: { years: [0, PRESENT], spaceScale: 1900, timeScale: 28 },
  "Dynastic history": { years: [-1000, 1900], spaceScale: 1800, timeScale: 55 },
  "Economic history": {
    years: [1200, PRESENT],
    spaceScale: 1200,
    timeScale: 24,
  },
  Epidemics: { years: [0, PRESENT], spaceScale: 1900, timeScale: 45 },
  Exploration: { years: [900, PRESENT], spaceScale: 2100, timeScale: 40 },
  Geopolitics: { years: [1800, PRESENT], spaceScale: 1500, timeScale: 20 },
  "Human rights": { years: [1800, PRESENT], spaceScale: 1800, timeScale: 22 },
  "Imperial politics": { years: [-500, 1000], spaceScale: 1700, timeScale: 45 },
  "Legal history": { years: [-2000, PRESENT], spaceScale: 1700, timeScale: 55 },
  Linguistics: { years: [1700, PRESENT], spaceScale: 1100, timeScale: 25 },
  Literature: { years: [900, PRESENT], spaceScale: 1100, timeScale: 35 },
  Migration: { years: [1500, PRESENT], spaceScale: 1800, timeScale: 30 },
  "Military history": {
    years: [-1000, PRESENT],
    spaceScale: 1900,
    timeScale: 42,
  },
  Music: { years: [1500, PRESENT], spaceScale: 700, timeScale: 12 },
  "Naval history": { years: [-100, PRESENT], spaceScale: 1900, timeScale: 38 },
  Philosophy: { years: [-600, PRESENT], spaceScale: 1500, timeScale: 55 },
  "Political history": {
    years: [1800, PRESENT],
    spaceScale: 1200,
    timeScale: 18,
  },
  "Political thought": {
    years: [1400, PRESENT],
    spaceScale: 1200,
    timeScale: 32,
  },
  Reformation: { years: [1450, 1700], spaceScale: 1200, timeScale: 28 },
  "Religious history": {
    years: [-1500, 1200],
    spaceScale: 1800,
    timeScale: 65,
  },
  Revolution: { years: [1700, PRESENT], spaceScale: 1400, timeScale: 22 },
  Science: { years: [1500, PRESENT], spaceScale: 1100, timeScale: 22 },
  "Social history": { years: [1700, PRESENT], spaceScale: 1400, timeScale: 22 },
  "State formation": { years: [900, PRESENT], spaceScale: 1700, timeScale: 35 },
  Technology: { years: [1400, PRESENT], spaceScale: 1100, timeScale: 22 },
  Theater: { years: [1500, PRESENT], spaceScale: 900, timeScale: 25 },
  Trade: { years: [1400, PRESENT], spaceScale: 1400, timeScale: 30 },
  Mathematics: { years: [-500, PRESENT], spaceScale: 1500, timeScale: 50 },
};

// These are not “harder” just because their subject is old. Their dates,
// locations, or scope are genuinely approximate, regional, or contested.
const QUESTION_RULES: Record<string, Calibration> = {
  "The earliest known writing appears on clay tablets in a Sumerian city.": {
    spaceScale: 3200,
    timeScale: 260,
  },
  "The largest of the pyramids is completed for the pharaoh Khufu.": {
    timeScale: 160,
  },
  "Suryavarman II begins what will become the largest religious monument on earth.":
    { spaceScale: 1900, timeScale: 70 },
  "Ptolemy completes his Geography.": { timeScale: 110 },
  "Dante completes the Divine Comedy.": { timeScale: 60 },
  "Chaucer begins The Canterbury Tales.": { timeScale: 60 },
  "Mansa Musa’s pilgrimage caravan spends so much gold it depresses the local currency for years.":
    { spaceScale: 2200, timeScale: 70 },
  "Potato blight triggers the Great Famine in Ireland.": {
    spaceScale: 2600,
    timeScale: 45,
  },
  "A tsunami devastates coasts around the Indian Ocean.": {
    spaceScale: 2800,
    timeScale: 24,
  },
  "The Cuban Missile Crisis brings the superpowers to the brink.": {
    spaceScale: 2600,
    timeScale: 24,
  },
  "The Rwandan genocide begins.": { spaceScale: 1900, timeScale: 25 },
  "Bubonic plague devastates the Eastern Roman capital under Justinian.": {
    timeScale: 80,
  },
  "The Black Death arrives in Sicily.": { timeScale: 55 },
  "Confucius dies in his home state of Lu.": { timeScale: 80 },
  "The Buddha preaches his first sermon in a deer park.": { timeScale: 110 },
};

const ROWS: Row[] = [
  [
    "Constantine wins the Battle of the Milvian Bridge.",
    312,
    41.94,
    12.47,
    "Rome, Italy",
    "Imperial politics",
    4,
  ],
  [
    "Pride and Prejudice is first published.",
    1813,
    51.51,
    -0.13,
    "London, England",
    "Literature",
    3,
  ],
  [
    "The Gutenberg Bible comes off the press.",
    1455,
    50,
    8.27,
    "Mainz, Germany",
    "Technology",
    4,
  ],
  [
    "Mansa Musa’s pilgrimage caravan spends so much gold it depresses the local currency for years.",
    1324,
    30.04,
    31.24,
    "Cairo, Egypt",
    "Economic history",
    3,
  ],
  [
    "Mehmed II’s cannon breach the walls of the thousand-year-old Byzantine capital.",
    1453,
    41.01,
    28.98,
    "Constantinople",
    "Military history",
    5,
  ],
  [
    "Jean-Jacques Dessalines proclaims the world’s first Black republic after a successful slave revolt.",
    1804,
    19.45,
    -72.68,
    "Gonaïves, Haiti",
    "Revolution",
    4,
  ],
  [
    "The Meiji Restoration is proclaimed.",
    1868,
    35.68,
    139.76,
    "Tokyo, Japan",
    "State formation",
    4,
  ],
  [
    "The Wright brothers make the first controlled powered flight.",
    1903,
    36.02,
    -75.67,
    "Kitty Hawk, USA",
    "Aviation",
    3,
  ],
  [
    "India becomes independent from British rule.",
    1947,
    28.61,
    77.21,
    "New Delhi, India",
    "Decolonization",
    5,
  ],
  [
    "A papal-brokered treaty divides the newly found world between two Iberian crowns.",
    1494,
    41.5,
    -5,
    "Tordesillas, Spain",
    "Diplomacy",
    4,
  ],
  [
    "Hiram Bingham arrives at an Inca mountain citadel after climbing from the Urubamba valley.",
    1911,
    -13.16,
    -72.55,
    "Cusco Region, Peru",
    "Archaeology",
    2,
  ],
  [
    "French soldiers uncover the Rosetta Stone.",
    1799,
    31.4,
    30.42,
    "Rashid, Egypt",
    "Linguistics",
    2,
  ],
  [
    "King John seals Magna Carta.",
    1215,
    51.44,
    -0.57,
    "Runnymede, England",
    "Legal history",
    4,
  ],
  [
    "King Cetshwayo’s Zulu army annihilates a British column beneath a rocky hill.",
    1879,
    -28.36,
    30.65,
    "Isandlwana, South Africa",
    "Colonial history",
    3,
  ],
  [
    "The earliest known writing appears on clay tablets in a Sumerian city.",
    -3200,
    31.32,
    45.64,
    "Uruk, Mesopotamia",
    "Writing systems",
    3,
  ],
  [
    "Akhenaten abandons the old gods and builds a new capital for the sun disc Aten.",
    -1346,
    27.65,
    30.9,
    "Amarna, Egypt",
    "Religious history",
    2,
  ],

  [
    "The gold rush begins after discovery at Sutter’s Mill.",
    1848,
    38.8,
    -120.89,
    "Coloma, USA",
    "Migration",
    2,
  ],
  [
    "Otto von Bismarck convenes the European powers to carve up Africa among themselves.",
    1884,
    52.52,
    13.4,
    "Berlin, Germany",
    "Geopolitics",
    5,
  ],
  [
    "Edward Jenner administers the first successful smallpox vaccination.",
    1796,
    51.71,
    -2.5,
    "Berkeley, England",
    "Medicine",
    2,
  ],
  [
    "A canal joining the Atlantic and Pacific opens to traffic.",
    1914,
    9.08,
    -79.68,
    "Panama",
    "Infrastructure",
    3,
  ],
  // ── Sport (calibrated tightly: modern, geographically specific) ──────────
  [
    "The first modern World Series begins.",
    1903,
    42.35,
    -71.1,
    "Boston, USA",
    "Baseball",
    2,
    { spaceScale: 700, timeScale: 18 },
  ],
  [
    "Jackie Robinson makes his major-league debut.",
    1947,
    40.67,
    -73.97,
    "Brooklyn, USA",
    "Baseball",
    2,
    { timeScale: 12 },
  ],
  [
    "Babe Ruth hits his sixtieth home run of the season.",
    1927,
    40.83,
    -73.93,
    "New York, USA",
    "Baseball",
    1,
    { spaceScale: 450 },
  ],
  [
    "Bobby Thomson hits the ‘Shot Heard ’Round the World’.",
    1951,
    40.83,
    -73.94,
    "Polo Grounds, New York",
    "Baseball",
    1,
  ],
  [
    "Cal Ripken Jr. breaks Lou Gehrig’s consecutive-games record.",
    1995,
    39.28,
    -76.62,
    "Baltimore, USA",
    "Baseball",
    1,
  ],
  [
    "The Red Sox win their first World Series in 86 years.",
    2004,
    38.63,
    -90.19,
    "St. Louis, USA",
    "Baseball",
    2,
  ],
  [
    "The first international cricket match is played.",
    1844,
    40.73,
    -74,
    "New York, USA",
    "Sport",
    1,
    { spaceScale: 800, timeScale: 20 },
  ],
  [
    "Spencer Gore wins the first championship at the world’s oldest tennis tournament.",
    1877,
    51.43,
    -0.21,
    "Wimbledon, England",
    "Tennis",
    2,
  ],
  [
    "The first Tour de France sets off.",
    1903,
    48.7,
    2.46,
    "Montgeron, France",
    "Cycling",
    2,
  ],
  [
    "Uruguay wins the first FIFA World Cup final.",
    1930,
    -34.89,
    -56.15,
    "Montevideo, Uruguay",
    "Football",
    3,
  ],
  [
    "Jesse Owens wins four gold medals at a Games staged as a fascist showcase.",
    1936,
    52.51,
    13.24,
    "Berlin, Germany",
    "Olympics",
    3,
  ],
  [
    "Roger Bannister runs the first sub-four-minute mile.",
    1954,
    51.75,
    -1.26,
    "Oxford, England",
    "Athletics",
    2,
  ],
  [
    "Seventeen-year-old Pelé wins the World Cup with Brazil.",
    1958,
    59.37,
    18.0,
    "Solna, Sweden",
    "Football",
    2,
  ],
  [
    "Muhammad Ali beats George Foreman in the ‘Rumble in the Jungle’.",
    1974,
    -4.33,
    15.31,
    "Kinshasa, Zaire",
    "Boxing",
    3,
  ],
  [
    "The US hockey team beats the Soviets in the ‘Miracle on Ice’.",
    1980,
    44.28,
    -73.98,
    "Lake Placid, USA",
    "Hockey",
    2,
  ],
  [
    "Maradona scores the ‘Hand of God’ goal.",
    1986,
    19.3,
    -99.15,
    "Mexico City, Mexico",
    "Football",
    3,
  ],
  // ── Ancient & classical ──────────────────────────────────────────────────
  [
    "The largest of the pyramids is completed for the pharaoh Khufu.",
    -2560,
    29.98,
    31.13,
    "Giza, Egypt",
    "Architecture",
    4,
    { timeScale: 120, spaceScale: 1500 },
  ],
  [
    "Hammurabi has his law code carved onto a basalt stele.",
    -1754,
    32.54,
    44.42,
    "Babylon, Mesopotamia",
    "Legal history",
    3,
    { timeScale: 100 },
  ],
  [
    "The Buddha preaches his first sermon in a deer park.",
    -528,
    25.38,
    83.02,
    "Sarnath, India",
    "Religious history",
    3,
    { timeScale: 80 },
  ],
  [
    "Confucius dies in his home state of Lu.",
    -479,
    35.6,
    116.99,
    "Qufu, China",
    "Philosophy",
    3,
    { timeScale: 60 },
  ],
  [
    "Miltiades and his outnumbered Athenians rout a Persian landing force on a coastal plain.",
    -490,
    38.15,
    23.97,
    "Marathon, Greece",
    "Military history",
    4,
  ],
  [
    "Socrates drinks hemlock after his conviction for impiety.",
    -399,
    37.97,
    23.72,
    "Athens, Greece",
    "Philosophy",
    4,
  ],
  [
    "Euclid compiles the Elements.",
    -300,
    31.2,
    29.92,
    "Alexandria, Egypt",
    "Mathematics",
    3,
    { timeScale: 60 },
  ],
  [
    "Qin Shi Huang unifies China under one emperor.",
    -221,
    34.33,
    108.7,
    "Xianyang, China",
    "Dynastic history",
    4,
  ],
  [
    "Hannibal leads an army across a mountain range during the Second Punic War.",
    -218,
    45.0,
    6.9,
    "Western Alps",
    "Military history",
    3,
    // The precise pass is debated, so this is intentionally regional.
    { spaceScale: 2500, timeScale: 60 },
  ],
  [
    "Julius Caesar is assassinated in the Senate.",
    -44,
    41.9,
    12.48,
    "Rome, Italy",
    "Imperial politics",
    5,
  ],
  [
    "Octavian’s fleet shatters that of Antony and Cleopatra.",
    -31,
    38.94,
    20.77,
    "Actium, Greece",
    "Naval history",
    3,
  ],
  [
    "Pliny the Elder dies as a volcanic eruption buries two Roman towns under ash and pumice.",
    79,
    40.75,
    14.49,
    "Pompeii, Italy",
    "Disaster",
    4,
  ],
  [
    "Work begins on Hadrian’s Wall.",
    122,
    55.0,
    -2.3,
    "Northern England",
    "Architecture",
    2,
  ],
  [
    "Ptolemy completes his Geography.",
    150,
    31.2,
    29.92,
    "Alexandria, Egypt",
    "Cartography",
    2,
    { timeScale: 60 },
  ],
  [
    "Bishops gather at the summons of emperor Constantine to settle the nature of Christ.",
    325,
    40.43,
    29.72,
    "Nicaea (İznik), Turkey",
    "Religious history",
    4,
  ],
  [
    "Alaric’s Visigoths sack a city that had not fallen to a foreign enemy in eight centuries.",
    410,
    41.9,
    12.48,
    "Rome, Italy",
    "Military history",
    3,
  ],
  [
    "A church council defines Christ as one person in two natures.",
    451,
    40.99,
    29.03,
    "Chalcedon, Turkey",
    "Religious history",
    2,
  ],
  [
    "Romulus Augustulus is deposed, ending the Western Roman Empire.",
    476,
    44.42,
    12.2,
    "Ravenna, Italy",
    "Imperial politics",
    4,
  ],
  [
    "Justinian issues his codification of Roman law.",
    529,
    41.01,
    28.98,
    "Constantinople",
    "Legal history",
    2,
  ],
  [
    "Hagia Sophia is dedicated.",
    537,
    41.01,
    28.98,
    "Constantinople",
    "Architecture",
    3,
  ],
  [
    "Bubonic plague devastates the Eastern Roman capital under Justinian.",
    541,
    41.01,
    28.98,
    "Constantinople",
    "Epidemics",
    2,
  ],
  // ── Medieval ─────────────────────────────────────────────────────────────
  [
    "Muhammad and his followers make the migration that begins the Islamic calendar.",
    622,
    24.47,
    39.61,
    "Medina, Arabia",
    "Religious history",
    4,
  ],
  [
    "Charles Martel halts an Umayyad advance into western Europe.",
    732,
    47.39,
    0.69,
    "Tours, France",
    "Military history",
    3,
  ],
  [
    "Norse raiders sack an island monastery, shocking Christian Europe.",
    793,
    55.67,
    -1.8,
    "Lindisfarne, England",
    "Military history",
    2,
  ],
  [
    "Pope Leo III crowns Charlemagne emperor on Christmas Day.",
    800,
    41.9,
    12.46,
    "Rome, Italy",
    "Imperial politics",
    4,
  ],
  [
    "Al-Khwarizmi writes his treatise on algebra.",
    820,
    33.34,
    44.4,
    "Baghdad, Iraq",
    "Mathematics",
    2,
    { timeScale: 40 },
  ],
  [
    "Norse voyagers establish a settlement on the far side of the North Atlantic.",
    1000,
    51.6,
    -55.53,
    "Newfoundland",
    "Exploration",
    2,
    { timeScale: 40 },
  ],
  [
    "The Great Schism divides the Eastern and Western churches.",
    1054,
    41.01,
    28.98,
    "Constantinople",
    "Religious history",
    3,
  ],
  [
    "William of Normandy defeats and kills the English king Harold.",
    1066,
    50.91,
    0.49,
    "Hastings, England",
    "Military history",
    5,
  ],
  [
    "Pope Urban II calls on Christendom to march east and retake Jerusalem.",
    1095,
    45.78,
    3.08,
    "Clermont, France",
    "Religious history",
    4,
  ],
  [
    "Godfrey of Bouillon’s crusaders storm the holy city after a five-week siege.",
    1099,
    31.78,
    35.23,
    "Jerusalem",
    "Military history",
    3,
  ],
  [
    "Suryavarman II begins what will become the largest religious monument on earth.",
    1113,
    13.41,
    103.87,
    "Angkor, Cambodia",
    "Architecture",
    3,
    { timeScale: 40 },
  ],
  [
    "Genghis Khan is proclaimed ruler of all the Mongols.",
    1206,
    48.4,
    108.7,
    "Onon River, Mongolia",
    "State formation",
    4,
  ],
  [
    "Hulagu Khan’s Mongols destroy the Abbasid capital and throw its libraries into the river.",
    1258,
    33.34,
    44.4,
    "Baghdad, Iraq",
    "Military history",
    3,
  ],
  [
    "Marco Polo arrives at the court of Kublai Khan.",
    1275,
    42.36,
    116.18,
    "Shangdu, China",
    "Exploration",
    2,
  ],
  [
    "Dante completes the Divine Comedy.",
    1320,
    44.42,
    12.2,
    "Ravenna, Italy",
    "Literature",
    3,
  ],
  [
    "The Mexica found a city on an island in a highland lake.",
    1325,
    19.43,
    -99.13,
    "Tenochtitlan, Mexico",
    "Dynastic history",
    2,
    { timeScale: 40 },
  ],
  [
    "Ibn Battuta, a 21-year-old jurist, begins a pilgrimage that will become a thirty-year journey.",
    1325,
    35.77,
    -5.8,
    "Tangier, Morocco",
    "Exploration",
    2,
  ],
  [
    "The Black Death arrives in Sicily.",
    1347,
    38.19,
    15.55,
    "Messina, Sicily",
    "Epidemics",
    4,
  ],
  [
    "Chaucer begins The Canterbury Tales.",
    1387,
    51.51,
    -0.12,
    "London, England",
    "Literature",
    2,
    { timeScale: 30 },
  ],
  [
    "Henry V’s longbowmen destroy a far larger French army in the mud.",
    1415,
    50.46,
    2.14,
    "Agincourt, France",
    "Military history",
    3,
  ],
  [
    "The Forbidden City is completed.",
    1420,
    39.91634,
    116.39716,
    "Beijing, China",
    "Architecture",
    3,
  ],
  [
    "Joan of Arc is burned at the stake.",
    1431,
    49.44,
    1.1,
    "Rouen, France",
    "Medieval history",
    3,
  ],
  // ── Early modern ─────────────────────────────────────────────────────────
  [
    "Columbus makes his first landfall in the Americas.",
    1492,
    24.1,
    -74.5,
    "The Bahamas",
    "Exploration",
    5,
  ],
  [
    "Vasco da Gama’s fleet arrives on India’s Malabar Coast, completing the first sea route from Europe.",
    1498,
    11.25,
    75.78,
    "Calicut, India",
    "Exploration",
    4,
  ],
  [
    "Leonardo begins the Mona Lisa.",
    1503,
    43.77,
    11.26,
    "Florence, Italy",
    "Art",
    3,
    { timeScale: 25 },
  ],
  [
    "Michelangelo unveils his David.",
    1504,
    43.77,
    11.26,
    "Florence, Italy",
    "Art",
    3,
  ],
  [
    "Machiavelli writes The Prince.",
    1513,
    43.77,
    11.25,
    "Florence, Italy",
    "Political thought",
    3,
  ],
  [
    "Martin Luther circulates the Ninety-five Theses.",
    1517,
    51.87,
    12.65,
    "Wittenberg, Germany",
    "Reformation",
    5,
  ],
  [
    "The Victoria returns to Spain, completing the first circumnavigation of the globe.",
    1522,
    36.53,
    -6.29,
    "Sanlúcar de Barrameda, Spain",
    "Exploration",
    3,
  ],
  [
    "Calvin publishes the Institutes of the Christian Religion.",
    1536,
    47.56,
    7.59,
    "Basel, Switzerland",
    "Reformation",
    2,
  ],
  [
    "Copernicus’s argument for a sun-centred cosmos goes to press.",
    1543,
    49.45,
    11.08,
    "Nuremberg, Germany",
    "Astronomy",
    4,
  ],
  [
    "Mercator publishes his world map projection.",
    1569,
    51.43,
    6.76,
    "Duisburg, Germany",
    "Cartography",
    2,
  ],
  [
    "The Holy League defeats the Ottoman fleet at Lepanto.",
    1571,
    38.24,
    21.32,
    "Gulf of Patras, Greece",
    "Naval history",
    3,
  ],
  [
    "The Spanish Armada is defeated.",
    1588,
    50.2,
    -4.1,
    "English Channel",
    "Naval history",
    4,
  ],
  [
    "Hamlet is first performed.",
    1601,
    51.51,
    -0.1,
    "London, England",
    "Theater",
    4,
    { timeScale: 15 },
  ],
  [
    "The Dutch East India Company is chartered.",
    1602,
    52.37,
    4.9,
    "Amsterdam, Netherlands",
    "Trade",
    3,
  ],
  [
    "Cervantes publishes Don Quixote.",
    1605,
    40.42,
    -3.7,
    "Madrid, Spain",
    "Literature",
    4,
  ],
  [
    "John Smith and his colonists plant England’s first lasting settlement in North America.",
    1607,
    37.21,
    -76.78,
    "Jamestown, Virginia",
    "Colonial history",
    4,
  ],
  [
    "Galileo turns his telescope on the heavens.",
    1609,
    45.41,
    11.88,
    "Padua, Italy",
    "Astronomy",
    4,
  ],
  [
    "Bohemian nobles throw Vilém Slavata and two fellow imperial officials from a castle window, igniting a thirty-year war.",
    1618,
    50.09,
    14.4,
    "Prague, Bohemia",
    "Military history",
    3,
  ],
  [
    "William Bradford and the Mayflower’s passengers land after a sixty-six-day crossing.",
    1620,
    41.96,
    -70.66,
    "Plymouth, Massachusetts",
    "Migration",
    4,
  ],
  [
    "Galileo is tried by the Inquisition.",
    1633,
    41.9,
    12.46,
    "Rome, Italy",
    "Science",
    3,
  ],
  [
    "Descartes publishes the Discourse on the Method.",
    1637,
    52.16,
    4.49,
    "Leiden, Netherlands",
    "Philosophy",
    3,
  ],
  [
    "Tulip mania collapses.",
    1637,
    52.38,
    4.64,
    "Haarlem, Netherlands",
    "Economic history",
    2,
  ],
  [
    "Rembrandt paints The Night Watch.",
    1642,
    52.37,
    4.89,
    "Amsterdam, Netherlands",
    "Art",
    2,
  ],
  [
    "The Peace of Westphalia ends the Thirty Years’ War.",
    1648,
    51.96,
    7.63,
    "Münster, Germany",
    "Diplomacy",
    4,
  ],
  [
    "Hobbes publishes Leviathan.",
    1651,
    51.51,
    -0.12,
    "London, England",
    "Political thought",
    2,
  ],
  [
    "The Taj Mahal is completed.",
    1653,
    27.17,
    78.04,
    "Agra, India",
    "Architecture",
    4,
  ],
  [
    "A fire in Thomas Farriner’s bakery destroys most of a great European capital.",
    1666,
    51.51,
    -0.09,
    "London, England",
    "Disaster",
    4,
  ],
  [
    "John III Sobieski’s relief army breaks an Ottoman siege of a Habsburg capital.",
    1683,
    48.21,
    16.37,
    "Vienna, Austria",
    "Military history",
    3,
  ],
  [
    "Newton publishes the Principia.",
    1687,
    51.51,
    -0.12,
    "London, England",
    "Physics",
    5,
  ],
  [
    "The Bank of England is founded.",
    1694,
    51.51,
    -0.09,
    "London, England",
    "Economic history",
    3,
  ],
  [
    "Tsar Peter the Great founds a new capital on marshland to face westward.",
    1703,
    59.94,
    30.31,
    "Saint Petersburg, Russia",
    "State formation",
    3,
  ],
  [
    "The South Sea Bubble bursts.",
    1720,
    51.51,
    -0.09,
    "London, England",
    "Economic history",
    2,
  ],
  [
    "Bach’s St Matthew Passion is first performed.",
    1727,
    51.34,
    12.37,
    "Leipzig, Germany",
    "Music",
    2,
  ],
  [
    "An earthquake, fire and tsunami wreck a European capital on All Saints’ Day.",
    1755,
    38.72,
    -9.14,
    "Lisbon, Portugal",
    "Disaster",
    3,
  ],
  [
    "Robert Clive’s victory hands the East India Company the revenues of Bengal.",
    1757,
    23.8,
    88.25,
    "Plassey, Bengal",
    "Colonial history",
    3,
  ],
  [
    "Rousseau publishes The Social Contract.",
    1762,
    52.37,
    4.9,
    "Amsterdam, Netherlands",
    "Political thought",
    2,
  ],
  [
    "James Watt patents his improved steam engine.",
    1769,
    55.86,
    -4.25,
    "Glasgow, Scotland",
    "Technology",
    4,
  ],
  [
    "Captain Cook makes his first landing on the east coast of a southern continent.",
    1770,
    -34.0,
    151.22,
    "Botany Bay, Australia",
    "Exploration",
    3,
  ],
  // ── Age of revolutions ───────────────────────────────────────────────────

  [
    "Adam Smith publishes The Wealth of Nations.",
    1776,
    51.51,
    -0.12,
    "London, England",
    "Economic history",
    4,
  ],
  [
    "Lavoisier names oxygen.",
    1777,
    48.86,
    2.35,
    "Paris, France",
    "Chemistry",
    2,
  ],
  [
    "Kant publishes the Critique of Pure Reason.",
    1781,
    54.71,
    20.51,
    "Königsberg, Prussia",
    "Philosophy",
    3,
  ],
  [
    "The United States Constitution is signed.",
    1787,
    39.95,
    -75.15,
    "Philadelphia, USA",
    "Constitutional history",
    5,
  ],
  [
    "Mozart’s Don Giovanni premieres.",
    1787,
    50.09,
    14.42,
    "Prague, Bohemia",
    "Music",
    3,
  ],
  [
    "A crowd storms the royal fortress held by Bernard-René de Launay and kills him.",
    1789,
    48.85,
    2.37,
    "Paris, France",
    "Revolution",
    5,
  ],
  [
    "Volta announces the electric battery.",
    1800,
    45.81,
    9.08,
    "Como, Italy",
    "Science",
    2,
  ],
  [
    "The Louisiana Purchase treaty is signed.",
    1803,
    48.86,
    2.34,
    "Paris, France",
    "Diplomacy",
    3,
  ],
  [
    "The Napoleonic Code comes into force.",
    1804,
    48.86,
    2.35,
    "Paris, France",
    "Legal history",
    3,
  ],
  [
    "Nelson destroys a combined French and Spanish fleet and is killed in the battle.",
    1805,
    36.25,
    -6.2,
    "Cape Trafalgar, Spain",
    "Naval history",
    4,
  ],
  [
    "The Brothers Grimm publish their fairy tales.",
    1812,
    51.32,
    9.5,
    "Kassel, Germany",
    "Literature",
    2,
  ],
  [
    "Napoleon suffers his final defeat and abdicates for the second time.",
    1815,
    50.68,
    4.41,
    "Waterloo, Belgium",
    "Military history",
    5,
  ],
  [
    "Mount Tambora erupts, bringing the ‘year without a summer’.",
    1815,
    -8.25,
    118.0,
    "Sumbawa, Indonesia",
    "Disaster",
    2,
  ],
  [
    "The victorious powers convene to redraw the map of Europe after Napoleon.",
    1815,
    48.21,
    16.37,
    "Vienna, Austria",
    "Diplomacy",
    3,
  ],
  [
    "Bolívar’s victory secures the independence of New Granada.",
    1819,
    5.45,
    -73.42,
    "Boyacá, Colombia",
    "Revolution",
    3,
  ],
  [
    "Champollion announces he has deciphered hieroglyphs.",
    1822,
    48.85,
    2.34,
    "Paris, France",
    "Linguistics",
    3,
  ],
  [
    "Beethoven’s Ninth Symphony premieres.",
    1824,
    48.21,
    16.37,
    "Vienna, Austria",
    "Music",
    4,
  ],
  [
    "The Erie Canal opens.",
    1825,
    42.65,
    -73.75,
    "Albany, New York",
    "Infrastructure",
    2,
  ],
  [
    "Niépce makes the earliest surviving photograph.",
    1826,
    46.75,
    4.85,
    "Saint-Loup-de-Varennes, France",
    "Technology",
    2,
    { timeScale: 8 },
  ],
  [
    "Britain abolishes slavery throughout its empire.",
    1833,
    51.5,
    -0.12,
    "London, England",
    "Legal history",
    4,
  ],
  [
    "Darwin’s survey ship reaches an equatorial volcanic archipelago.",
    1835,
    -0.83,
    -91.13,
    "Galápagos Islands",
    "Science",
    3,
  ],
  [
    "Morse sends the first telegraph message between cities.",
    1844,
    38.89,
    -77.01,
    "Washington, USA",
    "Communications",
    3,
  ],
  [
    "Potato blight triggers the Great Famine in Ireland.",
    1845,
    51.55,
    -9.27,
    "Skibbereen, Ireland",
    "Disaster",
    3,
  ],
  [
    "Ether anesthesia is demonstrated publicly.",
    1846,
    42.36,
    -71.07,
    "Boston, USA",
    "Medicine",
    2,
  ],
  [
    "Marx and Engels publish the Communist Manifesto.",
    1848,
    51.51,
    -0.12,
    "London, England",
    "Political thought",
    4,
  ],
  [
    "Revolution topples the July Monarchy and proclaims a second republic.",
    1848,
    48.86,
    2.35,
    "Paris, France",
    "Revolution",
    3,
  ],
  [
    "Elizabeth Cady Stanton reads her Declaration of Sentiments to the first women’s rights convention.",
    1848,
    42.91,
    -76.8,
    "Seneca Falls, New York",
    "Women’s history",
    3,
  ],
  [
    "The Great Exhibition opens in the Crystal Palace.",
    1851,
    51.5,
    -0.17,
    "London, England",
    "Technology",
    2,
  ],
  [
    "John Snow traces cholera to the Broad Street pump.",
    1854,
    51.51,
    -0.14,
    "London, England",
    "Medicine",
    2,
  ],
  [
    "Lord Cardigan leads a light cavalry brigade against the wrong guns.",
    1854,
    44.5,
    33.6,
    "Balaclava, Crimea",
    "Military history",
    2,
  ],
  [
    "Bessemer patents his steel-making process.",
    1856,
    53.38,
    -1.47,
    "Sheffield, England",
    "Technology",
    2,
  ],
  [
    "Cyrus West Field completes the first transatlantic telegraph cable.",
    1858,
    47.6,
    -52.7,
    "Newfoundland",
    "Communications",
    2,
  ],
  [
    "Darwin publishes On the Origin of Species.",
    1859,
    51.51,
    -0.12,
    "London, England",
    "Science",
    5,
  ],
  [
    "The Kingdom of Italy is proclaimed.",
    1861,
    45.07,
    7.69,
    "Turin, Italy",
    "State formation",
    3,
  ],
  [
    "Lincoln issues the Emancipation Proclamation.",
    1863,
    38.9,
    -77.04,
    "Washington, USA",
    "Civil rights",
    4,
  ],
  [
    "Union forces turn back Lee’s invasion of the North.",
    1863,
    39.81,
    -77.23,
    "Gettysburg, USA",
    "Military history",
    4,
  ],
  [
    "Abraham Lincoln is assassinated.",
    1865,
    38.9,
    -77.03,
    "Washington, USA",
    "Political history",
    4,
  ],
  [
    "Mendel presents his experiments on pea plants.",
    1865,
    49.2,
    16.61,
    "Brno, Moravia",
    "Biology",
    2,
  ],
  [
    "Tolstoy completes War and Peace.",
    1869,
    55.75,
    37.62,
    "Moscow, Russia",
    "Literature",
    3,
  ],
  [
    "The Suez Canal opens.",
    1869,
    30.59,
    32.27,
    "Port Said, Egypt",
    "Infrastructure",
    4,
  ],
  [
    "Leland Stanford drives a golden spike joining the first American transcontinental railroad.",
    1869,
    41.62,
    -112.55,
    "Promontory, Utah",
    "Infrastructure",
    3,
  ],
  [
    "Mendeleev publishes the periodic table.",
    1869,
    59.94,
    30.31,
    "Saint Petersburg, Russia",
    "Chemistry",
    3,
  ],
  [
    "Wilhelm I is proclaimed German emperor in a palace hall of mirrors.",
    1871,
    48.8,
    2.12,
    "Versailles, France",
    "State formation",
    4,
  ],
  [
    "Henry Morton Stanley arrives at a lakeside trading town and meets David Livingstone.",
    1871,
    -4.91,
    29.67,
    "Ujiji, Tanzania",
    "Exploration",
    2,
  ],
  [
    "Schliemann begins excavating Troy.",
    1871,
    39.96,
    26.24,
    "Hisarlik, Turkey",
    "Archaeology",
    2,
  ],
  [
    "Bell is granted a patent for the telephone.",
    1876,
    42.36,
    -71.06,
    "Boston, USA",
    "Communications",
    3,
  ],
  [
    "Edison demonstrates a practical incandescent lamp.",
    1879,
    40.53,
    -74.41,
    "Menlo Park, New Jersey",
    "Technology",
    3,
  ],
  [
    "A volcanic island explodes, and the sound is heard thousands of miles away.",
    1883,
    -6.1,
    105.42,
    "Krakatoa, Indonesia",
    "Disaster",
    3,
  ],
  [
    "The Brooklyn Bridge opens.",
    1883,
    40.71,
    -73.99,
    "New York, USA",
    "Engineering",
    2,
  ],
  [
    "James Murray publishes the first fascicle of a monumental English dictionary.",
    1884,
    51.75,
    -1.26,
    "Oxford, England",
    "Linguistics",
    2,
  ],
  [
    "Pasteur administers the first rabies vaccine.",
    1885,
    48.84,
    2.34,
    "Paris, France",
    "Medicine",
    3,
  ],
  [
    "A bomb thrown at a labour rally leads to the trial of August Spies and seven fellow anarchists.",
    1886,
    41.88,
    -87.64,
    "Chicago, USA",
    "Labor history",
    2,
  ],
  [
    "Zamenhof publishes the first book in Esperanto.",
    1887,
    52.23,
    21.01,
    "Warsaw, Poland",
    "Linguistics",
    1,
  ],
  [
    "The Eiffel Tower is completed.",
    1889,
    48.86,
    2.29,
    "Paris, France",
    "Architecture",
    4,
  ],
  [
    "New Zealand grants women the vote.",
    1893,
    -41.29,
    174.78,
    "Wellington, New Zealand",
    "Women’s history",
    3,
  ],
  [
    "Alfred Dreyfus is convicted of treason.",
    1894,
    48.85,
    2.32,
    "Paris, France",
    "Legal history",
    2,
  ],
  [
    "Röntgen discovers X-rays.",
    1895,
    49.79,
    9.94,
    "Würzburg, Germany",
    "Physics",
    3,
  ],
  [
    "The Lumière brothers hold the first public film screening.",
    1895,
    48.87,
    2.33,
    "Paris, France",
    "Film",
    3,
  ],
  [
    "Emperor Menelik II’s army destroys an Italian invasion force.",
    1896,
    14.16,
    38.9,
    "Adwa, Ethiopia",
    "Colonial history",
    3,
  ],
  [
    "The Curies announce the discovery of radium.",
    1898,
    48.84,
    2.35,
    "Paris, France",
    "Chemistry",
    3,
  ],
  // ── Twentieth century ────────────────────────────────────────────────────
  [
    "The Boxer Rebellion besieges the foreign legations.",
    1900,
    39.9,
    116.4,
    "Beijing, China",
    "Colonial history",
    2,
  ],
  [
    "Marconi receives the first transatlantic wireless signal.",
    1901,
    47.57,
    -52.7,
    "St John’s, Newfoundland",
    "Communications",
    3,
  ],
  [
    "Einstein publishes the special theory of relativity.",
    1905,
    46.95,
    7.45,
    "Bern, Switzerland",
    "Physics",
    4,
  ],
  [
    "An earthquake and the fires that follow gut a major Pacific-coast city.",
    1906,
    37.77,
    -122.42,
    "San Francisco, USA",
    "Disaster",
    3,
  ],
  [
    "Ford introduces the Model T.",
    1908,
    42.33,
    -83.05,
    "Detroit, USA",
    "Technology",
    3,
  ],
  [
    "A Norwegian expedition becomes the first to reach Earth’s southernmost point.",
    1911,
    -89.9,
    0,
    "South Pole",
    "Exploration",
    3,
  ],
  [
    "The Triangle Shirtwaist Factory burns.",
    1911,
    40.73,
    -73.99,
    "New York, USA",
    "Labor history",
    2,
  ],
  ["The Titanic sinks.", 1912, 41.73, -49.95, "North Atlantic", "Disaster", 4],
  [
    "Stravinsky’s Rite of Spring causes a riot at its premiere.",
    1913,
    48.87,
    2.31,
    "Paris, France",
    "Music",
    3,
  ],
  [
    "Archduke Franz Ferdinand is assassinated.",
    1914,
    43.86,
    18.43,
    "Sarajevo, Bosnia",
    "Geopolitics",
    5,
  ],
  [
    "Patrick Pearse seizes a post office and proclaims an Irish republic.",
    1916,
    53.35,
    -6.26,
    "Dublin, Ireland",
    "Revolution",
    3,
  ],
  [
    "Bolsheviks storm the Winter Palace.",
    1917,
    59.94,
    30.31,
    "Petrograd, Russia",
    "Revolution",
    5,
  ],
  [
    "The treaty imposing reparations and war guilt on Germany is signed.",
    1919,
    48.8,
    2.12,
    "Versailles, France",
    "Diplomacy",
    4,
  ],
  [
    "Prohibition takes effect in the United States.",
    1920,
    38.9,
    -77.04,
    "Washington, USA",
    "Social history",
    3,
  ],
  [
    "The Nineteenth Amendment is ratified.",
    1920,
    36.17,
    -86.78,
    "Nashville, USA",
    "Women’s history",
    3,
  ],
  [
    "KDKA makes the first scheduled commercial radio broadcast.",
    1920,
    40.44,
    -79.99,
    "Pittsburgh, USA",
    "Communications",
    2,
  ],
  [
    "Carter opens the tomb of Tutankhamun.",
    1922,
    25.74,
    32.6,
    "Valley of the Kings, Egypt",
    "Archaeology",
    3,
  ],
  [
    "Joyce’s Ulysses is published in full for the first time.",
    1922,
    48.85,
    2.34,
    "Paris, France",
    "Literature",
    2,
  ],
  [
    "Lindbergh lands at Le Bourget after crossing the Atlantic.",
    1927,
    48.97,
    2.44,
    "Paris, France",
    "Aviation",
    3,
  ],
  [
    "The Jazz Singer ushers in talking pictures.",
    1927,
    40.76,
    -73.98,
    "New York, USA",
    "Film",
    2,
  ],
  [
    "Fleming discovers penicillin.",
    1928,
    51.52,
    -0.17,
    "London, England",
    "Medicine",
    4,
  ],
  [
    "Wall Street crashes.",
    1929,
    40.71,
    -74.01,
    "New York, USA",
    "Economic history",
    5,
  ],
  [
    "Gandhi reaches the sea and makes salt in defiance of a British monopoly.",
    1930,
    20.92,
    72.83,
    "Dandi, India",
    "Decolonization",
    4,
  ],
  [
    "Hitler is appointed Chancellor of Germany.",
    1933,
    52.52,
    13.38,
    "Berlin, Germany",
    "Political history",
    4,
  ],
  [
    "The Hoover Dam is completed.",
    1936,
    36.02,
    -114.74,
    "Nevada–Arizona border",
    "Engineering",
    2,
  ],
  [
    "The BBC begins regular television broadcasts.",
    1936,
    51.58,
    -0.13,
    "Alexandra Palace, London",
    "Communications",
    2,
  ],
  [
    "Wolfram von Richthofen’s Condor Legion bombs a Basque market town.",
    1937,
    43.31,
    -2.68,
    "Guernica, Spain",
    "Military history",
    3,
  ],
  [
    "Picasso’s mural of an aerial bombing is unveiled at a world’s fair.",
    1937,
    48.86,
    2.29,
    "Paris, France",
    "Art",
    3,
  ],
  [
    "The airship Hindenburg bursts into flames while mooring.",
    1937,
    40.03,
    -74.35,
    "Lakehurst, New Jersey",
    "Aviation",
    2,
  ],
  [
    "The Golden Gate Bridge opens.",
    1937,
    37.82,
    -122.48,
    "San Francisco, USA",
    "Engineering",
    2,
  ],
  [
    "Lascaux’s painted caves are discovered.",
    1940,
    45.05,
    1.17,
    "Montignac, France",
    "Archaeology",
    2,
  ],
  [
    "John Maynard Keynes and delegates from forty-four nations fix a postwar monetary order at a mountain resort.",
    1944,
    44.26,
    -71.44,
    "Bretton Woods, New Hampshire",
    "Economic history",
    3,
  ],
  [
    "Roosevelt, Churchill and Stalin meet at a seaside palace to divide postwar Europe.",
    1945,
    44.47,
    34.14,
    "Yalta, Crimea",
    "Diplomacy",
    3,
  ],
  [
    "Paul Tibbets drops the first atomic bomb used in war.",
    1945,
    34.39,
    132.45,
    "Hiroshima, Japan",
    "Military history",
    5,
  ],
  [
    "The United Nations Charter is signed.",
    1945,
    37.78,
    -122.42,
    "San Francisco, USA",
    "Diplomacy",
    4,
  ],
  [
    "An international tribunal opens the trial of Hermann Göring and other surviving Nazi leaders.",
    1945,
    49.45,
    11.05,
    "Nuremberg, Germany",
    "Legal history",
    3,
  ],

  [
    "The transistor is invented at Bell Labs.",
    1947,
    40.68,
    -74.4,
    "Murray Hill, New Jersey",
    "Computing",
    3,
  ],
  [
    "The shepherd Muhammed edh-Dhib finds ancient scrolls in desert caves above a salt sea.",
    1947,
    31.74,
    35.46,
    "Qumran, West Bank",
    "Archaeology",
    2,
  ],
  [
    "Israel declares independence.",
    1948,
    32.07,
    34.78,
    "Tel Aviv",
    "State formation",
    4,
  ],
  [
    "General Lucius Clay orders Allied aircraft to supply a blockaded city entirely by air.",
    1948,
    52.47,
    13.4,
    "Berlin, Germany",
    "Geopolitics",
    3,
  ],
  [
    "Mao proclaims the People’s Republic of China.",
    1949,
    39.9,
    116.39,
    "Beijing, China",
    "State formation",
    5,
  ],
  [
    "Hillary and Tenzing reach the summit of the world’s highest mountain.",
    1953,
    27.99,
    86.93,
    "Mount Everest",
    "Exploration",
    4,
  ],
  [
    "The Supreme Court decides Brown v. Board of Education.",
    1954,
    38.89,
    -77.0,
    "Washington, USA",
    "Civil rights",
    3,
  ],

  [
    "Rosa Parks refuses to give up her bus seat.",
    1955,
    32.38,
    -86.31,
    "Montgomery, USA",
    "Civil rights",
    4,
  ],
  [
    "Six nations sign the treaty founding the European Economic Community.",
    1957,
    41.89,
    12.48,
    "Rome, Italy",
    "Diplomacy",
    3,
  ],
  [
    "Sputnik 1 is launched.",
    1957,
    45.92,
    63.34,
    "Baikonur, Kazakhstan",
    "Space exploration",
    5,
  ],
  [
    "OPEC is founded.",
    1960,
    33.32,
    44.37,
    "Baghdad, Iraq",
    "Economic history",
    2,
  ],
  [
    "Yuri Gagarin becomes the first human in space.",
    1961,
    45.92,
    63.34,
    "Baikonur, Kazakhstan",
    "Space exploration",
    4,
  ],
  [
    "Walter Ulbricht has barbed wire and concrete seal a divided city in two overnight.",
    1961,
    52.52,
    13.4,
    "Berlin, Germany",
    "Geopolitics",
    5,
  ],
  [
    "The Cuban Missile Crisis brings the superpowers to the brink.",
    1962,
    23.11,
    -82.37,
    "Havana, Cuba",
    "Geopolitics",
    4,
  ],
  [
    "Martin Luther King Jr. delivers ‘I Have a Dream’.",
    1963,
    38.89,
    -77.05,
    "Washington, USA",
    "Civil rights",
    4,
  ],
  [
    "The Beatles play Shea Stadium.",
    1965,
    40.76,
    -73.85,
    "New York, USA",
    "Music",
    2,
  ],
  [
    "Christiaan Barnard performs the first human heart transplant.",
    1967,
    -33.94,
    18.46,
    "Cape Town, South Africa",
    "Medicine",
    3,
  ],
  [
    "One Hundred Years of Solitude is published.",
    1967,
    -34.6,
    -58.38,
    "Buenos Aires, Argentina",
    "Literature",
    2,
  ],
  [
    "Apollo 11 lifts off for the Moon.",
    1969,
    28.60839,
    -80.60433,
    "Launch Complex 39A, Florida",
    "Space exploration",
    5,
  ],
  [
    "The Stonewall uprising begins.",
    1969,
    40.73,
    -74.0,
    "New York, USA",
    "Civil rights",
    3,
  ],
  [
    "Concorde makes its maiden flight.",
    1969,
    43.63,
    1.37,
    "Toulouse, France",
    "Aviation",
    2,
  ],
  [
    "Woodstock opens on a dairy farm.",
    1969,
    41.7,
    -74.88,
    "Bethel, New York",
    "Music",
    2,
  ],
  [
    "Dương Văn Minh surrenders as helicopters lift the last evacuees from an embassy roof.",
    1975,
    10.78,
    106.7,
    "Saigon, Vietnam",
    "Military history",
    4,
  ],
  [
    "Voyager 1 is launched.",
    1977,
    28.58322,
    -80.58308,
    "Space Launch Complex 41, Florida",
    "Space exploration",
    2,
  ],
  [
    "Anwar Sadat and Menachem Begin agree a framework for peace at an American presidential retreat.",
    1978,
    39.65,
    -77.47,
    "Camp David, Maryland",
    "Diplomacy",
    2,
  ],
  [
    "Shah Mohammad Reza Pahlavi flees into exile.",
    1979,
    35.69,
    51.39,
    "Tehran, Iran",
    "Revolution",
    4,
  ],
  [
    "Solidarity is born in the Gdańsk shipyard.",
    1980,
    54.36,
    18.65,
    "Gdańsk, Poland",
    "Labor history",
    3,
  ],
  [
    "The Challenger breaks apart after launch.",
    1986,
    28.627,
    -80.6208,
    "Launch Complex 39B, Florida",
    "Space exploration",
    3,
  ],
  [
    "A reactor supervised by Anatoly Dyatlov explodes during a safety test and scatters fallout across Europe.",
    1986,
    51.39,
    30.1,
    "Chernobyl, Ukraine",
    "Disaster",
    4,
  ],
  [
    "Tim Berners-Lee proposes the World Wide Web.",
    1989,
    46.23,
    6.05,
    "CERN, Geneva",
    "Computing",
    4,
  ],
  [
    "Tanks clear protesters from Tiananmen Square.",
    1989,
    39.9,
    116.39,
    "Beijing, China",
    "Political history",
    4,
  ],
  [
    "At a televised press conference, Günter Schabowski mistakenly says new travel rules take effect immediately.",
    1989,
    52.52,
    13.4,
    "Berlin, Germany",
    "Geopolitics",
    5,
  ],
  [
    "Nelson Mandela walks free.",
    1990,
    -33.79,
    18.97,
    "Paarl, South Africa",
    "Civil rights",
    4,
  ],
  [
    "The Hubble Space Telescope is launched.",
    1990,
    28.627,
    -80.6208,
    "Launch Complex 39B, Florida",
    "Space exploration",
    3,
  ],
  [
    "Mikhail Gorbachev resigns and the Soviet Union is dissolved.",
    1991,
    55.75,
    37.62,
    "Moscow, Russia",
    "Geopolitics",
    5,
  ],
  [
    "Andrew Wiles announces a proof of Fermat’s Last Theorem.",
    1993,
    52.21,
    0.12,
    "Cambridge, England",
    "Mathematics",
    2,
  ],
  [
    "The Rwandan genocide begins.",
    1994,
    -1.95,
    30.06,
    "Kigali, Rwanda",
    "Human rights",
    3,
  ],
  [
    "The Channel Tunnel opens.",
    1994,
    51.1,
    1.15,
    "Folkestone, England",
    "Engineering",
    2,
  ],
  [
    "Dolly the cloned sheep is announced.",
    1997,
    55.87,
    -3.2,
    "Roslin, Scotland",
    "Science",
    2,
  ],
  [
    "Governor Chris Patten hands Britain’s last major Asian colony back to China.",
    1997,
    22.28,
    114.16,
    "Hong Kong",
    "Decolonization",
    3,
  ],
  [
    "The Good Friday Agreement is signed.",
    1998,
    54.6,
    -5.93,
    "Belfast, Northern Ireland",
    "Diplomacy",
    2,
  ],
  [
    "The first module of the International Space Station is launched.",
    1998,
    45.92,
    63.34,
    "Baikonur, Kazakhstan",
    "Space exploration",
    2,
  ],
  // ── Twenty-first century ─────────────────────────────────────────────────
  [
    "Hijacked planes strike the World Trade Center.",
    2001,
    40.71,
    -74.01,
    "New York, USA",
    "Geopolitics",
    5,
  ],
  [
    "Euro notes and coins enter circulation.",
    2002,
    50.11,
    8.68,
    "Frankfurt, Germany",
    "Economic history",
    2,
  ],
  [
    "A tsunami devastates coasts around the Indian Ocean.",
    2004,
    3.32,
    95.85,
    "off Sumatra, Indonesia",
    "Disaster",
    3,
  ],
  [
    "Apple unveils the iPhone.",
    2007,
    37.78,
    -122.4,
    "San Francisco, USA",
    "Technology",
    3,
  ],

  [
    "Mohamed Bouazizi’s self-immolation sparks protests that topple president Zine El Abidine Ben Ali.",
    2011,
    36.81,
    10.17,
    "Tunis, Tunisia",
    "Revolution",
    3,
  ],
  [
    "An earthquake and tsunami trigger meltdowns at a coastal nuclear plant.",
    2011,
    37.42,
    141.03,
    "Fukushima, Japan",
    "Disaster",
    3,
  ],
];

// Deliberate additions to the thinner scheduled decks. Each prompt names a
// concrete historical act, and avoids giving away its answer location.
const EXPANDED_ROWS: Row[] = [
  [
    "The ancient Olympic Games are first recorded.",
    -776,
    37.638,
    21.63,
    "Olympia, Greece",
    "Sport",
    2,
    { years: [-1000, PRESENT], spaceScale: 1700, timeScale: 90 },
  ],
  [
    "The first FA Cup final is played.",
    1872,
    51.482,
    -0.112,
    "Kennington, England",
    "Football",
    2,
  ],
  [
    "National football associations establish FIFA.",
    1904,
    48.857,
    2.352,
    "Paris, France",
    "Football",
    2,
  ],
  [
    "The first game in the Basketball Association of America is played.",
    1946,
    43.663,
    -79.38,
    "Toronto, Canada",
    "Sport",
    2,
  ],
  [
    "The first Super Bowl is played.",
    1967,
    34.014,
    -118.287,
    "Los Angeles, USA",
    "Football",
    2,
  ],
  [
    "Billie Jean King defeats Bobby Riggs in the Battle of the Sexes.",
    1973,
    29.684,
    -95.407,
    "Houston, USA",
    "Tennis",
    2,
  ],
  [
    "Nadia Comăneci earns the first perfect 10 in Olympic gymnastics.",
    1976,
    45.496,
    -73.569,
    "Montreal, Canada",
    "Olympics",
    2,
  ],
  [
    "India win the Cricket World Cup final.",
    1983,
    51.529,
    -0.173,
    "London, England",
    "Sport",
    2,
  ],
  [
    "The first Rugby World Cup final is played.",
    1987,
    -36.875,
    174.744,
    "Auckland, New Zealand",
    "Sport",
    2,
  ],
  [
    "The first FIFA Women’s World Cup final is played.",
    1991,
    23.126,
    113.327,
    "Guangzhou, China",
    "Football",
    2,
  ],
  [
    "A fire starting in Catherine O’Leary’s barn destroys much of a great American city.",
    1871,
    41.881,
    -87.63,
    "Chicago, USA",
    "Disaster",
    2,
  ],
  [
    "Mount Pelée erupts and destroys a Caribbean port.",
    1902,
    14.74,
    -61.18,
    "Saint-Pierre, Martinique",
    "Disaster",
    2,
  ],
  [
    "A lethal winter smog settles over a major capital.",
    1952,
    51.507,
    -0.128,
    "London, England",
    "Disaster",
    2,
  ],
  [
    "A gas leak at a Union Carbide pesticide plant kills thousands as they sleep.",
    1984,
    23.258,
    77.413,
    "Bhopal, India",
    "Disaster",
    2,
  ],
  [
    "An oil tanker runs aground on Bligh Reef.",
    1989,
    60.84,
    -146.88,
    "Prince William Sound, Alaska",
    "Disaster",
    2,
  ],
  [
    "An earthquake kills over two hundred thousand people and topples the presidential palace of the poorest country in the Americas.",
    2010,
    18.54,
    -72.34,
    "Port-au-Prince, Haiti",
    "Disaster",
    2,
  ],
  [
    "The World Health Organization declares COVID-19 a pandemic.",
    2020,
    46.233,
    6.134,
    "Geneva, Switzerland",
    "Epidemics",
    2,
  ],
  [
    "Bartolomeu Dias rounds the southern tip of Africa.",
    1488,
    -34.356,
    18.474,
    "Cape of Good Hope, South Africa",
    "Exploration",
    2,
    { spaceScale: 2400, timeScale: 45 },
  ],
  [
    "Magellan’s expedition departs on the voyage that will circle the globe.",
    1519,
    37.389,
    -5.984,
    "Seville, Spain",
    "Exploration",
    2,
  ],
  [
    "Lewis and Clark reach the Pacific after crossing North America.",
    1805,
    46.19,
    -123.83,
    "Oregon Coast, USA",
    "Exploration",
    2,
    { spaceScale: 2200, timeScale: 30 },
  ],
  [
    "The bathyscaphe Trieste reaches the ocean’s deepest known point with two people aboard.",
    1960,
    11.35,
    142.2,
    "Challenger Deep, Pacific Ocean",
    "Exploration",
    2,
    { spaceScale: 2600, timeScale: 18 },
  ],
  [
    "Jane Goodall begins her field study of chimpanzees.",
    1960,
    -4.67,
    29.62,
    "Gombe Stream, Tanzania",
    "Exploration",
    2,
  ],
  [
    "Vesalius publishes a groundbreaking illustrated study of the human body.",
    1543,
    47.56,
    7.59,
    "Basel, Switzerland",
    "Medicine",
    2,
    { timeScale: 28 },
  ],
  [
    "Kepler publishes Astronomia nova, arguing that planets move in ellipses.",
    1609,
    50.075,
    14.438,
    "Prague, Bohemia",
    "Astronomy",
    2,
  ],
  [
    "Boyle publishes The Sceptical Chymist.",
    1661,
    51.507,
    -0.128,
    "London, England",
    "Chemistry",
    2,
  ],
  [
    "Bohr publishes his model of the atom.",
    1913,
    55.676,
    12.568,
    "Copenhagen, Denmark",
    "Physics",
    2,
  ],
  [
    "The United Nations adopts the Universal Declaration of Human Rights.",
    1948,
    48.857,
    2.352,
    "Paris, France",
    "Human rights",
    2,
  ],
  [
    "The United States Civil Rights Act is signed into law.",
    1964,
    38.897,
    -77.036,
    "Washington, USA",
    "Civil rights",
    2,
  ],
  [
    "The United States Voting Rights Act is signed into law.",
    1965,
    38.897,
    -77.036,
    "Washington, USA",
    "Civil rights",
    2,
  ],
  [
    "The first legal same-sex civil marriages take place.",
    2001,
    52.367,
    4.9,
    "Amsterdam, Netherlands",
    "Human rights",
    2,
  ],
  [
    "A suspension bridge links the island of Anglesey to mainland Wales.",
    1826,
    53.221,
    -4.16,
    "Menai Strait, Wales",
    "Engineering",
    2,
  ],
  [
    "The Empire State Building opens to the public.",
    1931,
    40.748,
    -73.986,
    "New York, USA",
    "Architecture",
    2,
  ],
  [
    "Jørn Utzon’s sail-shelled opera house opens after fourteen years of work.",
    1973,
    -33.856,
    151.215,
    "Sydney, Australia",
    "Architecture",
    2,
  ],
  [
    "The Burj Khalifa opens as the world’s tallest building.",
    2010,
    25.197,
    55.274,
    "Dubai, United Arab Emirates",
    "Architecture",
    2,
  ],
  [
    "Ibsen’s A Doll’s House has its first performance.",
    1879,
    55.676,
    12.568,
    "Copenhagen, Denmark",
    "Theater",
    2,
  ],
  [
    "The Original Dixieland Jass Band makes the first commercial jazz recording.",
    1917,
    40.75,
    -73.99,
    "New York, USA",
    "Music",
    2,
  ],
  [
    "The Boeing 707 makes its first flight.",
    1957,
    47.49,
    -122.22,
    "Renton, USA",
    "Aviation",
    2,
  ],
  [
    "IBM introduces the personal computer that becomes its standard PC.",
    1981,
    26.368,
    -80.128,
    "Boca Raton, USA",
    "Computing",
    2,
  ],
  [
    "Sony introduces the Walkman cassette player.",
    1979,
    35.676,
    139.65,
    "Tokyo, Japan",
    "Technology",
    2,
  ],
];

// Bank expansion. Aimed at the eras and lenses that were thinnest -- 500-1000
// AD, the eighteenth century, the post-2000 decades, and the "markets and
// modern life" and "crisis and recovery" decks -- plus a wider spread of
// subjects. Approximate dates and broad sites carry looser calibration so an
// unavoidably fuzzy answer is not scored as if it were a pinpoint.
const ADDED_ROWS: Row[] = [
  // European and North American additions. Rows dated before 1500 carry an
  // explicit window, since most FIELD_RULES windows begin later.

  // ── Prehistory and Rome ──────────────────────────────────────────────────
  [
    "A hunter later nicknamed Ötzi dies in a high mountain pass.",
    -3230,
    46.7786,
    10.8394,
    "Tisenjoch, Italy",
    "Archaeology",
    3,
    { years: [-4000, -1000], spaceScale: 1800, timeScale: 150 },
  ],
  [
    "Neolithic builders raise a circle of great sarsen stones.",
    -2500,
    51.1789,
    -1.8262,
    "Salisbury Plain, England",
    "Architecture",
    4,
    { years: [-4000, -500], spaceScale: 1800, timeScale: 200 },
  ],
  [
    "Titus inaugurates a new amphitheatre with a hundred days of games.",
    80,
    41.8902,
    12.4922,
    "Rome, Italy",
    "Architecture",
    4,
    { years: [-300, 600], timeScale: 30 },
  ],

  // ── The Middle Ages ─────────────────────────────────────────────────────
  [
    "Pope Gregory VII makes Henry IV wait barefoot in the snow.",
    1077,
    44.5583,
    10.4361,
    "Canossa, Italy",
    "Religious history",
    3,
    { years: [700, 1500], timeScale: 40 },
  ],
  [
    "Bishop Odo commissions an embroidered account of a conquest.",
    1077,
    49.2764,
    -0.7024,
    "Bayeux, France",
    "Art",
    3,
    { years: [700, 1500], timeScale: 45 },
  ],
  [
    "Abbot Suger begins rebuilding a royal abbey choir in a new pointed style.",
    1140,
    48.9362,
    2.3595,
    "Saint-Denis, France",
    "Architecture",
    3,
    { years: [800, 1600], timeScale: 45 },
  ],
  [
    "Bishop Maurice de Sully begins a cathedral on an island in the Seine.",
    1163,
    48.853,
    2.3499,
    "Paris, France",
    "Architecture",
    4,
    { years: [800, 1600], timeScale: 45 },
  ],
  [
    "Thomas Becket is murdered by four knights in his own cathedral.",
    1170,
    51.2798,
    1.0828,
    "Canterbury, England",
    "Religious history",
    4,
    { years: [800, 1600], timeScale: 40 },
  ],
  [
    "Jan van Eyck signs and dates a double portrait of a merchant couple.",
    1434,
    51.2093,
    3.2247,
    "Bruges, Flanders",
    "Art",
    3,
    { years: [1100, 1800], timeScale: 40 },
  ],
  [
    "Filippo Brunelleschi’s dome is closed over a cathedral crossing.",
    1436,
    43.7731,
    11.256,
    "Florence, Italy",
    "Architecture",
    4,
    { years: [1100, 1800], timeScale: 40 },
  ],
  [
    "William Caxton sets up the first printing press in England.",
    1476,
    51.4995,
    -0.1248,
    "Westminster, London",
    "Technology",
    3,
    { years: [1200, 1900], timeScale: 30 },
  ],
  [
    "Ferdinand and Isabella take the last Muslim city in Iberia.",
    1492,
    37.1773,
    -3.5986,
    "Granada, Spain",
    "Military history",
    4,
    { years: [1200, 1800], timeScale: 30 },
  ],

  // ── Renaissance and Reformation ─────────────────────────────────────────
  [
    "Michelangelo finishes painting a chapel ceiling for Pope Julius II.",
    1512,
    41.9029,
    12.4545,
    "Vatican City",
    "Art",
    4,
  ],
  [
    "Hernán Cortés enters the Aztec capital as an invited guest.",
    1519,
    19.4326,
    -99.1332,
    "Tenochtitlan, Mexico",
    "Colonial history",
    4,
  ],
  [
    "Henry VIII is declared supreme head of the church in England.",
    1534,
    51.4995,
    -0.1248,
    "Westminster, London",
    "Reformation",
    4,
  ],
  [
    "Pope Paul III opens a council to answer the reformers.",
    1545,
    46.0679,
    11.1211,
    "Trento, Italy",
    "Reformation",
    3,
  ],
  [
    "William Shakespeare’s company opens a new playhouse on the south bank.",
    1599,
    51.5081,
    -0.0972,
    "Southwark, London",
    "Theater",
    4,
  ],
  [
    "Christiaan Huygens builds the first pendulum clock.",
    1656,
    52.0705,
    4.3007,
    "The Hague, Netherlands",
    "Technology",
    3,
  ],
  [
    "Christopher Wren’s replacement cathedral is declared complete.",
    1711,
    51.5138,
    -0.0984,
    "London, England",
    "Architecture",
    4,
  ],
  [
    "Carl Linnaeus publishes a system for naming every living thing.",
    1735,
    52.3676,
    4.9041,
    "Amsterdam, Netherlands",
    "Biology",
    4,
  ],

  // ── Revolution and the long nineteenth century ──────────────────────────
  [
    "George Washington’s army crosses an icy river to attack at dawn.",
    1776,
    40.2206,
    -74.7597,
    "Trenton, New Jersey",
    "Military history",
    4,
  ],
  [
    "Edward Gibbon publishes the first volume of his history of Rome’s decline.",
    1776,
    51.5074,
    -0.1278,
    "London, England",
    "Literature",
    3,
  ],
  [
    "Cornwallis surrenders his army to Washington and Rochambeau.",
    1781,
    37.2387,
    -76.5097,
    "Yorktown, Virginia",
    "Military history",
    4,
  ],
  [
    "Delegates sign a new federal constitution after a summer of argument.",
    1787,
    39.9489,
    -75.15,
    "Philadelphia, USA",
    "Constitutional history",
    4,
  ],
  [
    "Mary Wollstonecraft argues in print for the rights of woman.",
    1792,
    51.5074,
    -0.1278,
    "London, England",
    "Women’s history",
    4,
  ],
  [
    "Johann Wolfgang von Goethe publishes the first part of his drama about a scholar’s bargain.",
    1808,
    50.9795,
    11.3235,
    "Weimar, Germany",
    "Literature",
    3,
  ],
  [
    "Michael Faraday demonstrates that a moving magnet induces a current.",
    1831,
    51.5093,
    -0.1428,
    "Mayfair, London",
    "Physics",
    4,
  ],
  [
    "Alexis de Tocqueville lands in America to study its democracy.",
    1831,
    40.7128,
    -74.006,
    "New York, USA",
    "Political thought",
    3,
  ],
  [
    "Charles Dickens begins serialising a novel about a workhouse orphan.",
    1837,
    51.5045,
    -0.0865,
    "London, England",
    "Literature",
    3,
  ],
  [
    "Giuseppe Verdi’s Rigoletto has its first performance.",
    1851,
    45.4341,
    12.3339,
    "Venice, Italy",
    "Music",
    3,
  ],
  [
    "Abraham Lincoln delivers a two-minute address at a battlefield cemetery.",
    1863,
    39.8221,
    -77.2306,
    "Gettysburg, USA",
    "Political history",
    4,
  ],
  [
    "James Clerk Maxwell publishes the equations of the electromagnetic field.",
    1865,
    51.5246,
    -0.134,
    "London, England",
    "Physics",
    4,
  ],
  [
    "Lee surrenders to Grant in a farmhouse parlour.",
    1865,
    37.3771,
    -78.7961,
    "Appomattox, Virginia",
    "Military history",
    4,
  ],
  [
    "Bismarck’s Prussia defeats Austria in seven weeks.",
    1866,
    50.2833,
    15.8167,
    "Königgrätz, Bohemia",
    "Military history",
    3,
  ],
  [
    "Claude Monet exhibits a harbour sunrise that gives a movement its name.",
    1874,
    48.8698,
    2.3316,
    "Paris, France",
    "Art",
    4,
  ],
  [
    "Antoni Gaudí takes charge of an unfinished expiatory temple.",
    1883,
    41.4036,
    2.1744,
    "Barcelona, Spain",
    "Architecture",
    3,
  ],
  [
    "Frédéric Auguste Bartholdi’s colossal copper statue is dedicated in a harbour.",
    1886,
    40.6892,
    -74.0445,
    "Liberty Island, New York",
    "Art",
    4,
  ],
  [
    "Vincent van Gogh paints a swirling night sky from an asylum window.",
    1889,
    43.7887,
    4.832,
    "Saint-Rémy-de-Provence, France",
    "Art",
    4,
  ],

  // ── The twentieth century ───────────────────────────────────────────────
  [
    "T. S. Eliot publishes a long poem about a barren modern world.",
    1922,
    51.5074,
    -0.1278,
    "London, England",
    "Literature",
    3,
  ],
  [
    "Edwin Hubble shows that other galaxies lie far beyond our own.",
    1924,
    34.2258,
    -118.057,
    "Mount Wilson, California",
    "Astronomy",
    4,
  ],
  [
    "Werner Heisenberg formulates his uncertainty principle.",
    1927,
    55.6969,
    12.5713,
    "Copenhagen, Denmark",
    "Physics",
    4,
  ],
  [
    "William Van Alen’s stainless spire tops out on a skyscraper.",
    1930,
    40.7516,
    -73.9755,
    "Manhattan, New York",
    "Architecture",
    3,
  ],
  [
    "Frank Lloyd Wright completes a house cantilevered over a waterfall.",
    1937,
    39.9064,
    -79.4681,
    "Mill Run, Pennsylvania",
    "Architecture",
    4,
  ],
  [
    "Winston Churchill becomes prime minister as Germany invades the Low Countries.",
    1940,
    51.5033,
    -0.1276,
    "Westminster, London",
    "Political history",
    4,
  ],
  [
    "Franklin Roosevelt and Winston Churchill agree a charter aboard warships at anchor.",
    1941,
    47.25,
    -54.0,
    "Placentia Bay, Newfoundland",
    "Diplomacy",
    3,
  ],
  [
    "Enrico Fermi’s team achieves the first controlled nuclear chain reaction.",
    1942,
    41.792,
    -87.6009,
    "Chicago, USA",
    "Physics",
    4,
  ],
  [
    "Rosalind Franklin photographs the X-ray diffraction pattern of DNA.",
    1952,
    51.5115,
    -0.116,
    "The Strand, London",
    "Biology",
    4,
  ],
  [
    "James Watson and Francis Crick propose a double helix for DNA.",
    1953,
    52.2043,
    0.1149,
    "Cambridge, England",
    "Biology",
    4,
  ],

  // Antiquity. Every row carries an explicit `years` window: most FIELD_RULES
  // windows start well after these dates, and a window that excludes the answer
  // makes the question unanswerable rather than merely hard.

  // ── Mesopotamia, Egypt and the Near East ─────────────────────────────────
  [
    "Sargon conquers the Sumerian cities and builds the first empire.",
    -2334,
    33.1,
    44.1,
    "Akkad, Mesopotamia",
    "State formation",
    3,
    { years: [-3200, -1200], spaceScale: 2600, timeScale: 120 },
  ],
  [
    "Hatshepsut has herself depicted as king and sends a fleet to Punt.",
    -1470,
    25.7381,
    32.6067,
    "Deir el-Bahari, Egypt",
    "Ancient history",
    3,
    { years: [-2200, -600], timeScale: 90 },
  ],
  [
    "Thutmose III defeats a coalition of city-states at a hill-town gate.",
    -1457,
    32.5847,
    35.1836,
    "Megiddo, Canaan",
    "Military history",
    3,
    { years: [-2000, -600], timeScale: 80 },
  ],
  [
    "Tutankhamun is buried hurriedly in a small tomb.",
    -1323,
    25.7402,
    32.6014,
    "Valley of the Kings, Egypt",
    "Ancient history",
    4,
    { years: [-2000, -500], timeScale: 70 },
  ],
  [
    "Ramesses II fights the Hittites to a standstill at a river crossing.",
    -1274,
    34.5567,
    36.5233,
    "Kadesh, Syria",
    "Military history",
    3,
    { years: [-1800, -400], timeScale: 70 },
  ],
  [
    "Hattusili III and Ramesses II agree the earliest surviving peace treaty.",
    -1259,
    40.0187,
    34.6151,
    "Hattusa, Anatolia",
    "Diplomacy",
    3,
    { years: [-1800, -400], timeScale: 70 },
  ],
  [
    "Ashurnasirpal II opens his new palace with a banquet for tens of thousands.",
    -879,
    36.0983,
    43.3283,
    "Nimrud, Mesopotamia",
    "Architecture",
    2,
    { years: [-1400, -200], timeScale: 70 },
  ],
  [
    "Nebuchadnezzar II destroys the temple of a small hill kingdom and deports its people.",
    -587,
    31.7784,
    35.2354,
    "Jerusalem",
    "Military history",
    4,
    { years: [-1200, 0], timeScale: 45 },
  ],
  [
    "Xenophon takes command of ten thousand stranded Greek mercenaries and begins the march north.",
    -401,
    33.0,
    44.3,
    "Cunaxa, Mesopotamia",
    "Military history",
    3,
    { years: [-800, 0], spaceScale: 2400, timeScale: 45 },
  ],
  [
    "Alexander the Great dies at thirty-two, and his generals begin to divide the empire.",
    -323,
    32.5355,
    44.4275,
    "Babylon, Mesopotamia",
    "Imperial politics",
    4,
    { years: [-700, 100], timeScale: 35 },
  ],
  [
    "Zenobia’s armies seize Egypt and challenge Rome.",
    270,
    34.552,
    38.2687,
    "Palmyra, Syria",
    "Military history",
    3,
    { years: [0, 700], timeScale: 45 },
  ],

  // ── Greece and the Hellenistic world ─────────────────────────────────────
  [
    "Leonidas and his Spartans hold a narrow pass to the last man.",
    -480,
    38.7961,
    22.5367,
    "Thermopylae, Greece",
    "Military history",
    4,
    { years: [-900, -100], timeScale: 40 },
  ],
  [
    "Themistocles lures the Persian fleet into a narrow strait.",
    -480,
    37.95,
    23.53,
    "Salamis, Greece",
    "Naval history",
    4,
    { years: [-900, -100], timeScale: 40 },
  ],
  [
    "Pericles begins the temple that will crown his city’s citadel.",
    -447,
    37.9715,
    23.7267,
    "Athens, Greece",
    "Architecture",
    4,
    { years: [-900, -100], timeScale: 40 },
  ],
  [
    "Herodotus completes his enquiries into the wars between Greeks and Persians.",
    -430,
    39.7167,
    16.4667,
    "Thurii, Italy",
    "Literature",
    3,
    { years: [-900, 0], timeScale: 50 },
  ],
  [
    "Hippocrates teaches medicine on his home island.",
    -420,
    36.8933,
    27.2883,
    "Kos, Greece",
    "Medicine",
    3,
    { years: [-900, 0], timeScale: 60 },
  ],
  [
    "Plato founds his school in a grove outside the city walls.",
    -387,
    37.99,
    23.71,
    "Athens, Greece",
    "Philosophy",
    4,
    { years: [-800, 0], timeScale: 40 },
  ],
  [
    "Aristotle begins tutoring the young Alexander.",
    -343,
    40.6833,
    22.1333,
    "Mieza, Macedonia",
    "Philosophy",
    3,
    { years: [-800, 0], timeScale: 40 },
  ],
  [
    "Pytheas returns from a voyage to the northern edge of the known world.",
    -325,
    43.2965,
    5.3698,
    "Massalia, Gaul",
    "Exploration",
    3,
    { years: [-800, 200], spaceScale: 2200, timeScale: 60 },
  ],
  [
    "Eratosthenes measures the circumference of the earth.",
    -240,
    31.2001,
    29.9187,
    "Alexandria, Egypt",
    "Mathematics",
    4,
    { years: [-700, 200], timeScale: 45 },
  ],
  [
    "Archimedes is killed by a soldier during the sack of his city.",
    -212,
    37.0755,
    15.2866,
    "Syracuse, Sicily",
    "Mathematics",
    4,
    { years: [-600, 200], timeScale: 40 },
  ],
  [
    "Cleopatra VII takes her own life, and Egypt becomes a Roman province.",
    -30,
    31.2001,
    29.9187,
    "Alexandria, Egypt",
    "Imperial politics",
    4,
    { years: [-400, 300], timeScale: 30 },
  ],
  [
    "Hanno the Navigator returns from a voyage down the west African coast.",
    -500,
    36.8528,
    10.3233,
    "Carthage, Tunisia",
    "Exploration",
    3,
    { years: [-900, 0], spaceScale: 2200, timeScale: 70 },
  ],

  // ── Rome ────────────────────────────────────────────────────────────────
  [
    "Scipio Africanus defeats Hannibal in north Africa.",
    -202,
    36.3,
    9.5,
    "Zama, Tunisia",
    "Military history",
    4,
    { years: [-600, 200], spaceScale: 2000, timeScale: 35 },
  ],
  [
    "Scipio Aemilianus razes Rome’s great rival at the end of the third Punic war.",
    -146,
    36.8528,
    10.3233,
    "Carthage, Tunisia",
    "Military history",
    3,
    { years: [-600, 200], timeScale: 35 },
  ],
  [
    "Spartacus is killed and his slave rising is crushed.",
    -71,
    40.7333,
    15.1833,
    "Lucania, Italy",
    "Social history",
    3,
    { years: [-400, 300], spaceScale: 2000, timeScale: 30 },
  ],
  [
    "Julius Caesar crosses a small river with one legion and begins a civil war.",
    -49,
    44.0925,
    12.4022,
    "Rubicon, Italy",
    "Military history",
    4,
    { years: [-400, 200], timeScale: 25 },
  ],
  [
    "Octavian is granted the name Augustus and the powers of a first emperor.",
    -27,
    41.8925,
    12.4853,
    "Rome, Italy",
    "Imperial politics",
    4,
    { years: [-400, 300], timeScale: 25 },
  ],
  [
    "Boudica’s rebels burn the chief Roman colony in Britain.",
    60,
    51.8892,
    0.9042,
    "Colchester, England",
    "Military history",
    3,
    { years: [-200, 500], timeScale: 30 },
  ],
  [
    "Titus’s legions storm the city and destroy its second temple.",
    70,
    31.7784,
    35.2354,
    "Jerusalem",
    "Military history",
    4,
    { years: [-200, 500], timeScale: 30 },
  ],
  [
    "The last defenders of a desert fortress die rather than surrender to Flavius Silva.",
    73,
    31.3156,
    35.3539,
    "Masada, Judaea",
    "Military history",
    3,
    { years: [-200, 500], timeScale: 30 },
  ],
  [
    "Trajan’s legions complete the conquest of a rich kingdom north of the Danube.",
    106,
    45.6222,
    23.3111,
    "Sarmizegetusa, Dacia",
    "Military history",
    3,
    { years: [-100, 600], timeScale: 35 },
  ],
  [
    "Marcus Aurelius writes his private notebooks while on campaign.",
    175,
    48.11,
    16.86,
    "Carnuntum, Austria",
    "Philosophy",
    3,
    { years: [0, 700], timeScale: 40 },
  ],
  [
    "Diocletian divides the empire’s rule between four men.",
    293,
    40.7654,
    29.9408,
    "Nicomedia, Turkey",
    "Imperial politics",
    3,
    { years: [0, 700], timeScale: 35 },
  ],
  [
    "Constantine dedicates a new capital on the Bosphorus.",
    330,
    41.0082,
    28.9784,
    "Constantinople",
    "State formation",
    4,
    { years: [0, 700], timeScale: 30 },
  ],
  [
    "Augustine completes The City of God.",
    426,
    36.8833,
    7.75,
    "Hippo Regius, Numidia",
    "Philosophy",
    3,
    { years: [100, 900], timeScale: 40 },
  ],
  [
    "Patrick begins his mission to convert the Irish.",
    432,
    54.3503,
    -6.6528,
    "Armagh, Ireland",
    "Religious history",
    3,
    { years: [100, 900], timeScale: 50 },
  ],
  [
    "Attila’s Huns are checked by Aetius and his Visigothic allies.",
    451,
    48.9566,
    4.3634,
    "Châlons, France",
    "Military history",
    3,
    { years: [100, 900], spaceScale: 2000, timeScale: 35 },
  ],
  [
    "Clovis is baptised and unites the Franks under one Christian king.",
    496,
    49.2583,
    4.0317,
    "Reims, France",
    "Religious history",
    3,
    { years: [200, 1000], timeScale: 40 },
  ],

  // ── China and India ─────────────────────────────────────────────────────

  // ── The Americas ────────────────────────────────────────────────────────
  [
    "The Nazca people begin cutting vast figures into the desert floor.",
    -100,
    -14.53,
    -75.19,
    "Palpa, Peru",
    "Art",
    3,
    { years: [-800, 600], spaceScale: 2000, timeScale: 120 },
  ],
  [
    "The Pyramid of the Sun is completed in a vast planned city.",
    200,
    19.6925,
    -98.8438,
    "Teotihuacan, Mexico",
    "Architecture",
    3,
    { years: [-400, 900], timeScale: 100 },
  ],
  [
    "K’inich Janaab’ Pakal is entombed beneath a Maya pyramid.",
    683,
    17.4839,
    -92.0464,
    "Palenque, Mexico",
    "Architecture",
    3,
    { years: [200, 1200], timeScale: 50 },
  ],

  // ── Asia: antiquity and the classical world ──────────────────────────────
  [
    "Ashurbanipal assembles a great library of clay tablets.",
    -650,
    36.36,
    43.15,
    "Nineveh, Mesopotamia",
    "Ancient history",
    3,
    { timeScale: 50 },
  ],
  [
    "Cyrus the Great takes the greatest city of Mesopotamia and issues a cylinder proclaiming his rule.",
    -539,
    32.54,
    44.42,
    "Babylon, Mesopotamia",
    "Imperial politics",
    4,
    { years: [-1000, 500] },
  ],
  [
    "Darius I begins a new ceremonial capital in the Persian highlands.",
    -518,
    29.94,
    52.89,
    "Persepolis, Iran",
    "Architecture",
    3,
    { timeScale: 35 },
  ],
  [
    "Alexander the Great routs Darius III in the battle that opens Persia to him.",
    -331,
    36.36,
    43.25,
    "Gaugamela, Iraq",
    "Military history",
    4,
  ],

  // ── Asia: 500-1500 ───────────────────────────────────────────────────────

  // ── Asia: early modern ───────────────────────────────────────────────────
  [
    "Stamford Raffles founds a British trading post at the tip of the Malay peninsula.",
    1819,
    1.29,
    103.85,
    "Singapore",
    "Colonial history",
    3,
  ],

  // ── Asia: modern ─────────────────────────────────────────────────────────

  // ── Africa ───────────────────────────────────────────────────────────────
  [
    "Henry Morton Stanley reaches the Atlantic after descending a great African river.",
    1877,
    -5.85,
    13.06,
    "Boma, Congo",
    "Exploration",
    3,
  ],

  // ── South America ────────────────────────────────────────────────────────
  [
    "Pachacuti begins turning the Inca realm into an empire.",
    1438,
    -13.52,
    -71.98,
    "Cusco, Peru",
    "State formation",
    3,
    { timeScale: 35 },
  ],
  [
    "Francisco Pizarro seizes the Inca ruler Atahualpa.",
    1532,
    -7.16,
    -78.51,
    "Cajamarca, Peru",
    "Colonial history",
    4,
  ],
  [
    "Túpac Amaru II leads a great indigenous revolt against Spanish rule.",
    1780,
    -14.15,
    -71.42,
    "Tinta, Peru",
    "Revolution",
    3,
  ],
  [
    "José de San Martín completes his crossing of the Andes and beats the royalists.",
    1817,
    -33.03,
    -70.68,
    "Chacabuco, Chile",
    "Military history",
    3,
  ],
  [
    "Pedro I declares independence from Portugal beside a stream.",
    1822,
    -23.59,
    -46.61,
    "Ipiranga, Brazil",
    "Revolution",
    3,
  ],
  [
    "Getúlio Vargas takes power in a revolution.",
    1930,
    -22.91,
    -43.17,
    "Rio de Janeiro, Brazil",
    "Revolution",
    3,
  ],
  [
    "Eva Perón renounces the vice-presidency before a vast crowd.",
    1951,
    -34.61,
    -58.38,
    "Buenos Aires, Argentina",
    "Social history",
    3,
  ],
  [
    "Salvador Allende dies as tanks shell the presidential palace.",
    1973,
    -33.44,
    -70.65,
    "Santiago, Chile",
    "Geopolitics",
    3,
  ],
  [
    "Luis Urzúa is the last of thirty-three miners lifted out after sixty-nine days underground.",
    2010,
    -27.18,
    -70.49,
    "Copiapó, Chile",
    "Disaster",
    3,
  ],

  // ── Oceania and the Pacific ──────────────────────────────────────────────
  [
    "Abel Tasman becomes the first European to sight the islands Māori call Aotearoa.",
    1642,
    -40.8,
    172.9,
    "South Island, New Zealand",
    "Exploration",
    3,
    { spaceScale: 2000 },
  ],
  [
    "James Cook is killed in a fight on a Pacific beach.",
    1779,
    19.48,
    -155.93,
    "Kealakekua Bay, Hawaii",
    "Exploration",
    3,
  ],
  [
    "William Hobson and Māori chiefs sign a treaty ceding sovereignty to the Crown.",
    1840,
    -35.27,
    174.09,
    "Waitangi, New Zealand",
    "Diplomacy",
    3,
  ],
  [
    "Ned Kelly is captured after a siege in his homemade armour.",
    1880,
    -36.46,
    146.22,
    "Glenrowan, Australia",
    "Social history",
    3,
  ],
  [
    "Edmund Barton is sworn in as a federated Australia’s first prime minister.",
    1901,
    -33.9,
    151.23,
    "Sydney, Australia",
    "State formation",
    3,
  ],

  // ── Filling the 500-1000 gap ─────────────────────────────────────────────
  [
    "Harun al-Rashid receives an embassy sent by Charlemagne.",
    801,
    33.31,
    44.36,
    "Baghdad, Iraq",
    "Diplomacy",
    3,
    { years: [500, 1200], timeScale: 30 },
  ],
  [
    "Alfred the Great defeats Guthrum’s Danes and saves Wessex.",
    878,
    51.28,
    -2.1,
    "Edington, England",
    "Military history",
    3,
  ],
  [
    "Abd al-Rahman III proclaims himself caliph of the west.",
    929,
    37.88,
    -4.78,
    "Córdoba, Spain",
    "Imperial politics",
    3,
  ],
  [
    "Otto I is crowned Holy Roman emperor.",
    962,
    41.9,
    12.45,
    "Rome, Italy",
    "Imperial politics",
    3,
  ],

  // ── Filling the post-2000 gap ────────────────────────────────────────────
  [
    "Barack Obama is inaugurated as the first Black president of the United States.",
    2009,
    38.89,
    -77.01,
    "Washington, USA",
    "Civil rights",
    4,
  ],
  [
    "Elon Musk’s SpaceX lands an orbital rocket booster upright for the first time.",
    2015,
    28.49,
    -80.54,
    "Landing Zone 1, Florida",
    "Space exploration",
    3,
  ],
  [
    "Greta Thunberg begins her school strike outside a national parliament.",
    2018,
    59.33,
    18.07,
    "Stockholm, Sweden",
    "Social history",
    3,
  ],
  [
    "Özlem Türeci and Uğur Şahin see their mRNA vaccine approved for use.",
    2020,
    49.99,
    8.25,
    "Mainz, Germany",
    "Medicine",
    4,
  ],

  // ── Europe and North America: computing ─────────────────────────────────
  [
    "Ada Lovelace publishes her notes describing a general-purpose computing machine.",
    1843,
    51.51,
    -0.13,
    "London, England",
    "Computing",
    3,
  ],
  [
    "Herman Hollerith’s punched-card machines tabulate a national census.",
    1890,
    38.89,
    -77.03,
    "Washington, USA",
    "Computing",
    3,
  ],
  [
    "Alan Turing’s codebreakers bring the first Bombe into service against Enigma.",
    1940,
    51.997,
    -0.741,
    "Bletchley Park, England",
    "Computing",
    4,
  ],
  [
    "John Mauchly and J. Presper Eckert unveil the ENIAC.",
    1946,
    39.95,
    -75.19,
    "Philadelphia, USA",
    "Computing",
    3,
  ],
  [
    "John Bardeen and Walter Brattain demonstrate the first transistor.",
    1947,
    40.68,
    -74.4,
    "Murray Hill, New Jersey",
    "Computing",
    4,
  ],
  [
    "Douglas Engelbart demonstrates the mouse, hypertext and video calls in one sitting.",
    1968,
    37.78,
    -122.42,
    "San Francisco, USA",
    "Computing",
    3,
  ],

  [
    "Steve Jobs introduces the first iPhone.",
    2007,
    37.78,
    -122.4,
    "San Francisco, USA",
    "Technology",
    4,
  ],

  // ── Europe and North America: markets and money ─────────────────────────

  [
    "Jay Gould and James Fisk’s attempt to corner the gold market collapses.",
    1869,
    40.71,
    -74.01,
    "New York, USA",
    "Economic history",
    3,
  ],
  [
    "Charles Ponzi is arrested as his investment scheme unravels.",
    1920,
    42.36,
    -71.06,
    "Boston, USA",
    "Economic history",
    3,
  ],
  [
    "Franklin Roosevelt closes every bank in the country for four days.",
    1933,
    38.9,
    -77.04,
    "Washington, USA",
    "Economic history",
    4,
  ],
  [
    "Richard Nixon ends the dollar’s convertibility into gold.",
    1971,
    39.65,
    -77.47,
    "Camp David, Maryland",
    "Economic history",
    4,
  ],
  [
    "Richard Fuld’s Lehman Brothers files for bankruptcy.",
    2008,
    40.76,
    -73.98,
    "New York, USA",
    "Economic history",
    4,
  ],

  // ── Aviation ─────────────────────────────────────────────────────────────
  [
    "Louis Blériot lands after the first aeroplane flight across the English Channel.",
    1909,
    51.13,
    1.32,
    "Dover, England",
    "Aviation",
    3,
  ],
  [
    "Amelia Earhart lands after flying the Atlantic alone.",
    1932,
    55.05,
    -7.28,
    "Culmore, Northern Ireland",
    "Aviation",
    4,
  ],
  [
    "Chuck Yeager flies faster than sound.",
    1947,
    34.9,
    -117.88,
    "Rogers Dry Lake, California",
    "Aviation",
    4,
  ],

  // ── Sport and spectacle ──────────────────────────────────────────────────
  [
    "Pierre de Coubertin’s revived Olympic Games open.",
    1896,
    37.97,
    23.74,
    "Athens, Greece",
    "Olympics",
    3,
  ],
  [
    "Jack Johnson beats Tommy Burns to become heavyweight champion.",
    1908,
    -33.89,
    151.23,
    "Sydney, Australia",
    "Boxing",
    3,
  ],

  [
    "Bob Beamon jumps 8.90 metres at high altitude.",
    1968,
    19.43,
    -99.13,
    "Mexico City, Mexico",
    "Olympics",
    3,
  ],

  // ── Crisis, disease and the dug-up past ─────────────────────────────────

  [
    "Annie Moore is the first immigrant processed at a new inspection station.",
    1892,
    40.7,
    -74.04,
    "Ellis Island, New York",
    "Migration",
    3,
  ],
  [
    "George Soper identifies a cook as a healthy carrier of typhoid.",
    1907,
    40.75,
    -73.98,
    "New York, USA",
    "Epidemics",
    3,
  ],
  [
    "Captain Edward Smith’s liner strikes an iceberg and sinks.",
    1912,
    41.73,
    -49.95,
    "North Atlantic",
    "Disaster",
    4,
    { spaceScale: 1600 },
  ],

  [
    "Jonas Salk announces a successful polio vaccine trial.",
    1955,
    42.28,
    -83.74,
    "Ann Arbor, Michigan",
    "Medicine",
    4,
  ],
  [
    "Mary Leakey finds an early hominin skull in an east African ravine.",
    1959,
    -2.99,
    35.35,
    "Olduvai Gorge, Tanzania",
    "Archaeology",
    3,
  ],

  // ── The eighteenth century ───────────────────────────────────────────────
  [
    "Maria Theresa inherits the Habsburg lands and is attacked within months.",
    1740,
    48.21,
    16.37,
    "Vienna, Austria",
    "Dynastic history",
    3,
  ],
  [
    "Denis Diderot publishes the first volume of his Encyclopédie.",
    1751,
    48.85,
    2.34,
    "Paris, France",
    "Political thought",
    3,
  ],
  [
    "Catherine the Great seizes the Russian throne from her husband.",
    1762,
    59.94,
    30.31,
    "Saint Petersburg, Russia",
    "Imperial politics",
    3,
    { years: [1600, 1900] },
  ],

  [
    "Thomas Jefferson’s declaration of independence is adopted.",
    1776,
    39.95,
    -75.15,
    "Philadelphia, USA",
    "Constitutional history",
    4,
  ],

  // ── The 500-1000 gap in Europe ──────────────────────────────────────────
  [
    "Belisarius takes the Gothic capital of Italy for Justinian.",
    540,
    44.42,
    12.2,
    "Ravenna, Italy",
    "Military history",
    3,
  ],
  [
    "Bede completes his history of the English church and people.",
    731,
    54.98,
    -1.47,
    "Jarrow, England",
    "Literature",
    3,
    { years: [400, 1200], timeScale: 30 },
  ],
  [
    "Cyril and Methodius begin preaching in a Slavic tongue.",
    863,
    48.9,
    17.1,
    "Great Moravia",
    "Religious history",
    3,
    { spaceScale: 2000, timeScale: 30 },
  ],
];

export const EVENTS: Event[] = [...ROWS, ...EXPANDED_ROWS, ...ADDED_ROWS].map(
  ([title, year, lat, lon, place, field, weight, calibration]) => ({
    title,
    year,
    lat,
    lon,
    place,
    field,
    weight,
    ...FIELD_RULES[field],
    ...calibration,
    ...QUESTION_RULES[title],
  }),
);

// A short answer-side note turns an opaque clue into a useful historical
// moment. These stay out of the prompt so the location and date are still
// genuinely guessed rather than read.
export const EVENT_CONTEXT: Record<string, string> = {
  "At a televised press conference, Günter Schabowski mistakenly says new travel rules take effect immediately.":
    "Schabowski had been given a draft easing East German travel restrictions. His muddled answer sent people to the checkpoints that night, accelerating the fall of the Berlin Wall.",
  "Ibn Battuta, a 21-year-old jurist, begins a pilgrimage that will become a thirty-year journey.":
    "His first destination was Mecca, but the journey grew into travels across North and East Africa, the Middle East, Central Asia, India, and China. Later he dictated the Rihla, one of history’s great travel accounts.",
  "Hannibal leads an army across a mountain range during the Second Punic War.":
    "Hannibal’s force crossed from Gaul into Italy with elephants, an audacious opening move in the Second Punic War. The exact pass is still debated, so the game accepts a broad Alpine region.",
};

const e = (
  title: string,
  year: number,
  lat: number,
  lon: number,
  place: string,
  field: string,
): Event => ({ title, year, lat, lon, place, field, weight: 3 });
export const FOCUSES: Focus[] = [
  {
    name: "The Second World War",
    note: "A global war, fifteen years close",
    years: [1931, 1946],
    view: { lat: 45, lon: 25, distance: 2.65 },
    deck: [
      e(
        "Germany invades Poland.",
        1939,
        52.23,
        21.01,
        "Warsaw, Poland",
        "European theater",
      ),
      e(
        "The evacuation from Dunkirk begins.",
        1940,
        51.04,
        2.38,
        "Dunkirk, France",
        "European theater",
      ),
      e(
        "Japan attacks Pearl Harbor.",
        1941,
        21.36,
        -157.95,
        "Oahu, Hawaii",
        "Pacific theater",
      ),
      e(
        "The Battle of Stalingrad ends.",
        1943,
        48.71,
        44.51,
        "Stalingrad",
        "Eastern Front",
      ),
      e(
        "Allied forces land in Normandy.",
        1944,
        49.34,
        -0.62,
        "Normandy, France",
        "European theater",
      ),
      e(
        "Paul Tibbets drops the first atomic bomb used in war.",
        1945,
        34.39,
        132.45,
        "Hiroshima, Japan",
        "Pacific theater",
      ),
      e(
        "Japan formally surrenders aboard the USS Missouri.",
        1945,
        35.29,
        139.67,
        "Tokyo Bay",
        "Pacific theater",
      ),
    ],
  },
  {
    name: "Japanese history",
    note: "An archipelago across twelve centuries",
    years: [700, 1950],
    view: { lat: 37, lon: 138, distance: 2.05 },
    deck: [
      e(
        "The imperial capital moves to Heian-kyō.",
        794,
        35.01,
        135.77,
        "Kyoto, Japan",
        "Heian period",
      ),
      e(
        "The Kamakura shogunate is established.",
        1192,
        35.32,
        139.55,
        "Kamakura, Japan",
        "Kamakura period",
      ),
      e(
        "The Battle of Sekigahara establishes Tokugawa dominance.",
        1600,
        35.37,
        136.46,
        "Sekigahara, Japan",
        "Sengoku period",
      ),
      e(
        "The Tokugawa shogunate is established.",
        1603,
        35.68,
        139.76,
        "Edo, Japan",
        "Edo period",
      ),
      e(
        "Commodore Perry enters Edo Bay.",
        1853,
        35.24,
        139.72,
        "Uraga, Japan",
        "Bakumatsu",
      ),
      e(
        "The Meiji Restoration is proclaimed.",
        1868,
        35.68,
        139.76,
        "Tokyo, Japan",
        "Meiji period",
      ),
      e(
        "The Great Kantō earthquake strikes.",
        1923,
        35.44,
        139.64,
        "Kantō, Japan",
        "Social history",
      ),
    ],
  },
  {
    name: "The Scientific Revolution",
    note: "Observation changes the world",
    years: [1450, 1750],
    view: { lat: 49, lon: 11, distance: 2.3 },
    deck: [
      e(
        "Copernicus’s De revolutionibus is published.",
        1543,
        54.35,
        18.65,
        "Gdańsk, Poland",
        "Astronomy",
      ),
      e(
        "Tycho Brahe begins building Uraniborg.",
        1576,
        55.91,
        12.69,
        "Hven, Denmark",
        "Astronomy",
      ),
      e(
        "Galileo demonstrates his telescope in Venice.",
        1609,
        45.44,
        12.33,
        "Venice, Italy",
        "Astronomy",
      ),
      e(
        "William Harvey publishes his account of blood circulation.",
        1628,
        50.11,
        8.68,
        "Frankfurt, Germany",
        "Medicine",
      ),
      e(
        "The Royal Society is founded.",
        1660,
        51.51,
        -0.12,
        "London, England",
        "Institutions",
      ),
      e(
        "Newton’s Principia is published.",
        1687,
        51.51,
        -0.12,
        "London, England",
        "Physics",
      ),
      e(
        "Leeuwenhoek reports microorganisms.",
        1676,
        52.01,
        4.36,
        "Delft, Netherlands",
        "Microscopy",
      ),
    ],
  },
];
